//! why: spell -> class lookup, baked in at compile time like `parser.rs`
//!
//! Generated by `~/eql/build_spell_classes.py` from a full wiki scrape
//! (1,928 pages). Keyed by base (rank-stripped) name -- 1,431 entries,
//! rank variants merged via the same stripping logic `Ingest` itself uses.
//! Build script drops empty/bogus `classes` fields and folds
//! Shadowknight/Shadow Knight spelling variants.
//!
//! 4 hand-verified exceptions layered on top (Harm Touch, Leech,
//! Malaisement, Blast of Cold -- real spells missing from the scrape).
//! `Origin` deliberately excluded: an every-class AA, not real evidence.

use std::collections::HashMap;
use std::sync::OnceLock;

const CLASS_DATA_JSON: &str = include_str!("../../../packs/spell_classes.json");

static CLASS_DATA: OnceLock<HashMap<String, Vec<String>>> = OnceLock::new();

/// why: empty means unknown spell, not zero eligible classes
pub fn classes_for(base_spell_name: &str) -> &'static [String] {
    let map = CLASS_DATA.get_or_init(|| {
        serde_json::from_str(CLASS_DATA_JSON).unwrap_or_else(|e| {
            // why: malformed embedded data is a build bug, fail loud
            panic!("packs/spell_classes.json failed to parse: {e}")
        })
    });
    map.get(base_spell_name)
        .map(|v| v.as_slice())
        .unwrap_or(&[])
}
