//! why: spell -> class lookup, baked in at compile time like `parser.rs`
//!
//! Generated by `~/eql/build_spell_classes.py` from a full wiki scrape
//! (1,928 pages). Keyed by base (rank-stripped) name -- 1,431 entries,
//! rank variants merged via the same stripping logic `Ingest` itself uses.
//! Build script drops empty/bogus `classes` fields and folds
//! Shadowknight/Shadow Knight spelling variants.
//!
//! 4 hand-verified exceptions layered on top (Harm Touch, Leech,
//! Malaisement, Blast of Cold -- real spells missing from the scrape).
//! `Origin` deliberately excluded: an every-class AA, not real evidence.
//!
//! Case-folded only: "Ice Strike" (Shaman) and "Icestrike" (Wizard) are
//! two real spells, so nothing here may strip whitespace (classpool.rs).
use crate::classpool::{self, ClassPool};
use std::sync::OnceLock;

static POOL: OnceLock<ClassPool> = OnceLock::new();

fn pool() -> &'static ClassPool {
    POOL.get_or_init(|| {
        ClassPool::load(
            "spell_classes.json",
            include_str!("../../../packs/spell_classes.json"),
            classpool::ci,
            &[],
        )
    })
}

/// why: empty means unknown name, not zero eligible classes
pub fn classes_for(base_spell_name: &str) -> &'static [String] {
    pool().classes_for(base_spell_name)
}
