//! why: item catalog, baked in at compile time like `classdata.rs`
//!
//! Generated by `~/eql/scrape.py` -- re-run and re-copy to pick up wiki changes.

use serde::Deserialize;
use std::collections::HashMap;
use std::sync::OnceLock;

const ITEM_DATA_JSON: &str = include_str!("../../../packs/items.json");

#[derive(Debug, Clone, Deserialize)]
pub struct ItemDrop {
    pub zone: String,
    #[serde(default)]
    pub mobs: Vec<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Item {
    pub id: String,
    pub name: String,
    #[serde(default)]
    pub tags: Vec<String>,
    #[serde(default)]
    pub slots: Vec<String>,
    /// why: may be `["ALL"]` or `"ALL_EXCEPT"`+codes; only `usable_by` interprets it
    #[serde(default)]
    pub classes: Vec<String>,
    #[serde(default)]
    pub races: Vec<String>,
    #[serde(default)]
    pub stats: HashMap<String, f64>,
    /// why: effect slot -> raw scrape value; `gearplanner` only checks key presence
    #[serde(default)]
    pub effects: HashMap<String, serde_json::Value>,
    #[serde(default)]
    pub drops: Vec<ItemDrop>,
    /// why: single primary era; `eras`/`available_from` carry the fuller
    /// picture `gearplanner::era_index` actually resolves against
    pub era: Option<String>,
    #[serde(default)]
    pub eras: Vec<String>,
    pub available_from: Option<String>,
    pub skill: Option<String>,
    pub dmg: Option<f64>,
    pub delay: Option<f64>,
    pub wt: Option<f64>,
    pub size: Option<String>,
    #[serde(default)]
    pub vendors: Vec<String>,
    #[serde(default)]
    pub quests: Vec<String>,
    #[serde(default)]
    pub crafted_by: Vec<String>,
    pub url: Option<String>,
    pub icon: Option<String>,
    /// why: unfiltered wiki categories; only used by `gearplanner::on_server`
    /// to check for "Non-P99 Content" (wiki's marker for unimplemented data)
    #[serde(default)]
    pub categories: Vec<String>,
    /// why: true if craft ingredient starts "Imbued " -- Imbue not live yet
    #[serde(default)]
    pub requires_imbue: bool,
}

#[derive(Debug, Deserialize)]
struct ItemsDoc {
    items: Vec<Item>,
}

static ITEMS: OnceLock<Vec<Item>> = OnceLock::new();

/// why: every scraped item, parsed once; malformed data fails loud
pub fn items() -> &'static [Item] {
    ITEMS
        .get_or_init(|| {
            let doc: ItemsDoc = serde_json::from_str(ITEM_DATA_JSON)
                .unwrap_or_else(|e| panic!("packs/items.json failed to parse: {e}"));
            doc.items
        })
        .as_slice()
}

/// why: lookup by id -- lets `gearplanner::item_at_tier` re-derive stats
/// without carrying the whole `Item` across the IPC boundary
pub fn by_id(id: &str) -> Option<&'static Item> {
    items().iter().find(|it| it.id == id)
}
