//! Wires the scraped item catalog (`packs/items.json`) into the live app,
//! the same `include_str!`-at-compile-time pattern `classdata.rs`/
//! `monsterdata.rs` already use and for the same reason: an installed
//! desktop app has no reliable working directory to read a data file from
//! at launch.
//!
//! `packs/items.json` is generated by `~/eql/scrape.py`, not hand-written --
//! re-run it and re-copy the output here to pick up wiki changes.

use serde::Deserialize;
use std::collections::HashMap;
use std::sync::OnceLock;

const ITEM_DATA_JSON: &str = include_str!("../../../packs/items.json");

#[derive(Debug, Clone, Deserialize)]
pub struct ItemDrop {
    pub zone: String,
    #[serde(default)]
    pub mobs: Vec<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Item {
    pub id: String,
    pub name: String,
    #[serde(default)]
    pub tags: Vec<String>,
    #[serde(default)]
    pub slots: Vec<String>,
    /// Class-code list (`"WIZ"`, `"ENC"`, ...) -- may instead be `["ALL"]`
    /// (every class) or start with `"ALL_EXCEPT"` followed by the excluded
    /// codes (every class *but* these). See `usable_by`, which is the only
    /// place that distinction should ever be interpreted -- everywhere
    /// else this is just the raw list the scrape produced.
    #[serde(default)]
    pub classes: Vec<String>,
    #[serde(default)]
    pub races: Vec<String>,
    #[serde(default)]
    pub stats: HashMap<String, f64>,
    /// Effect slot ("focus"/"click"/"worn"/"proc") -> whatever the scrape
    /// captured for it. Never interpreted beyond "is this key present" in
    /// `crate::gearplanner`'s scoring (see `SCORED_EFFECTS`'s doc there) --
    /// kept as a loose value rather than a fixed shape since that's all
    /// this app currently needs from it.
    #[serde(default)]
    pub effects: HashMap<String, serde_json::Value>,
    #[serde(default)]
    pub drops: Vec<ItemDrop>,
    /// The category-derived era (single value, whichever the scrape
    /// picked as primary). `eras`/`available_from` below carry the fuller
    /// picture `gearplanner::era_index` actually resolves against -- see
    /// that function's doc for why a single `era` field alone
    /// under-resolves items that carry more than one era category.
    pub era: Option<String>,
    #[serde(default)]
    pub eras: Vec<String>,
    pub available_from: Option<String>,
    pub skill: Option<String>,
    pub dmg: Option<f64>,
    pub delay: Option<f64>,
    pub wt: Option<f64>,
    pub size: Option<String>,
    #[serde(default)]
    pub vendors: Vec<String>,
    #[serde(default)]
    pub quests: Vec<String>,
    #[serde(default)]
    pub crafted_by: Vec<String>,
    pub url: Option<String>,
    pub icon: Option<String>,
    /// Raw wiki categories the scrape kept around unfiltered (era/slot/
    /// class categories all get parsed into their own dedicated fields
    /// above -- this is what's left). The one thing this app currently
    /// reads it for: `gearplanner::on_server` checking for
    /// `"Non-P99 Content"`, the wiki's own marker for pages carried over
    /// from a P99 dataset this fork never actually implemented -- see
    /// that function's doc for why era filtering alone can't catch these.
    #[serde(default)]
    pub categories: Vec<String>,
    /// why: true if any craft ingredient starts with "Imbued " -- Imbue
    /// spells aren't live on this server yet. Derived at scrape time, not
    /// a name/category guess -- see `scrape.py`'s own comment on this field.
    #[serde(default)]
    pub requires_imbue: bool,
}

#[derive(Debug, Deserialize)]
struct ItemsDoc {
    items: Vec<Item>,
}

static ITEMS: OnceLock<Vec<Item>> = OnceLock::new();

/// Every item the scrape carries. Parses the embedded JSON once, on first
/// use -- a malformed embedded file is a build-time data bug, loud and
/// immediate, same stance `classdata.rs` takes on its own pack.
pub fn items() -> &'static [Item] {
    ITEMS
        .get_or_init(|| {
            let doc: ItemsDoc = serde_json::from_str(ITEM_DATA_JSON)
                .unwrap_or_else(|e| panic!("packs/items.json failed to parse: {e}"));
            doc.items
        })
        .as_slice()
}

/// One catalog item by its scrape-assigned `id` -- what `gearplanner::
/// item_at_tier` needs to re-derive an arbitrary item's stats at a
/// caller-chosen tier without the caller having to carry the whole `Item`
/// (a `ScoredItemDto`/`ItemDto` only ever has the id, not the source
/// struct) across the IPC boundary and back.
pub fn by_id(id: &str) -> Option<&'static Item> {
    items().iter().find(|it| it.id == id)
}
