//! why: NPC bestiary, baked in like `itemdata.rs`/`monsterdata.rs`/`zonedata.rs`
//!
//! Generated by `~/eql/scrape_eqlwiki_npcs.py`. 6,532 entries, one per
//! "Named Mob" page -- distinct from `monsterdata.rs`'s narrower
//! item-scrape-sourced mob->drops lookup, no stats/location/loot detail there.

use regex::Regex;
use serde::{Deserialize, Serialize};
use std::sync::OnceLock;

const NPC_DATA_JSON: &str = include_str!("../../../packs/npcs.json");

/// why: richer than `itemdata::ItemDrop` -- from the NPC page's own drop
/// table, carries rarity/drop-chance the item scrape never has
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct KnownLoot {
    pub item: String,
    pub rarity: Option<String>,
    pub stack: Option<f64>,
    pub chance_per_kill: Option<f64>,
    pub chance_per_drop: Option<f64>,
}

/// why: presentation-ready like `zonedata::Zone` -- doubles as parse target and DTO
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Npc {
    pub id: String,
    pub name: String,
    pub url: String,
    pub race: Option<String>,
    pub class: Option<String>,
    pub level: Option<String>,
    /// why: None common for multi-zone NPCs; `location` carries those instead
    pub zone: Option<String>,
    pub location: Option<String>,
    pub respawn_time: Option<String>,
    pub aggro_radius: Option<f64>,
    pub run_speed: Option<f64>,
    #[serde(rename = "AC")]
    pub ac: Option<i64>,
    #[serde(rename = "HP")]
    pub hp: Option<i64>,
    pub hp_regen: Option<i64>,
    pub mana_regen: Option<i64>,
    pub attacks_per_round: Option<i64>,
    pub attack_speed: Option<String>,
    pub damage_per_hit: Option<String>,
    pub special: Option<String>,
    #[serde(default)]
    pub known_loot: Vec<KnownLoot>,
    pub imagefilename: Option<String>,
    #[serde(default)]
    pub images: Vec<String>,
    pub era: Option<String>,
    #[serde(default)]
    pub categories: Vec<String>,
}

#[derive(Deserialize)]
struct NpcsDoc {
    npcs: Vec<Npc>,
}

static NPCS: OnceLock<Vec<Npc>> = OnceLock::new();

/// why: every scraped NPC, parsed once; malformed data fails loud
pub fn npcs() -> &'static [Npc] {
    NPCS.get_or_init(|| {
        let doc: NpcsDoc = serde_json::from_str(NPC_DATA_JSON)
            .unwrap_or_else(|e| panic!("packs/npcs.json failed to parse: {e}"));
        doc.npcs
    })
    .as_slice()
}

/// why: parses free-text spawn notation into real points; descriptive
/// text ("Various", "Need Info") yields none. `%` weighting dropped --
/// multiple spawns render as multiple equal markers.
pub fn parse_locations(location: &str) -> Vec<(f32, f32, Option<f32>)> {
    static RE: OnceLock<Regex> = OnceLock::new();
    let re = RE.get_or_init(|| {
        Regex::new(r"\(?(-?\d+(?:\.\d+)?),\s*(-?\d+(?:\.\d+)?)(?:,\s*(-?\d+(?:\.\d+)?))?\)?")
            .unwrap()
    });
    re.captures_iter(location)
        .filter_map(|c| {
            let x: f32 = c.get(1)?.as_str().parse().ok()?;
            let y: f32 = c.get(2)?.as_str().parse().ok()?;
            let z: Option<f32> = c.get(3).and_then(|m| m.as_str().parse().ok());
            Some((x, y, z))
        })
        .collect()
}

/// why: loosely resembles `target`, deliberately broad -- wiki names and
/// EQ shortcodes have no derivable relationship, so surfaced as
/// toggle-able candidates rather than auto-applied
pub fn candidate_zones(target: &str) -> Vec<String> {
    fn norm(s: &str) -> String {
        s.chars()
            .filter(|c| c.is_ascii_alphanumeric())
            .map(|c| c.to_ascii_lowercase())
            .collect()
    }
    let t = norm(target);
    if t.is_empty() {
        return Vec::new();
    }
    let mut candidates: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    for n in npcs() {
        let Some(z) = &n.zone else { continue };
        let nz = norm(z);
        if !nz.is_empty() && (nz.contains(&t) || t.contains(&nz)) {
            candidates.insert(z.clone());
        }
    }
    candidates.into_iter().collect()
}

/// why: exact match -- fuzzy work already happened in `candidate_zones`;
/// multi-spawn mobs contribute one marker per point, not deduplicated
pub fn markers_for_zone(zone: &str) -> Vec<(String, f32, f32, Option<f32>)> {
    let mut out = Vec::new();
    for n in npcs() {
        if n.zone.as_deref() != Some(zone) {
            continue;
        }
        let Some(loc) = &n.location else { continue };
        for (x, y, z) in parse_locations(loc) {
            out.push((n.name.clone(), x, y, z));
        }
    }
    out
}

#[cfg(test)]
mod location_tests {
    use super::*;

    /// why: real strings pulled straight from packs/npcs.json
    #[test]
    fn parses_every_real_shape_seen_in_the_scrape() {
        assert_eq!(
            parse_locations("(836, -2879)"),
            vec![(836.0, -2879.0, None)]
        );
        assert_eq!(
            parse_locations("25% @ (55, -573)"),
            vec![(55.0, -573.0, None)]
        );
        assert_eq!(
            parse_locations("-59.93, 433.90, 9.75"),
            vec![(-59.93, 433.90, Some(9.75))]
        );
        assert_eq!(
            parse_locations("(667, 146, -51.59)"),
            vec![(667.0, 146.0, Some(-51.59))]
        );
        assert_eq!(parse_locations("1182, -834"), vec![(1182.0, -834.0, None)]);

        let multi = parse_locations("8% @ (-78, 164), 8% @ (-20, 1), 8% @ (-389, 2804)");
        assert_eq!(
            multi,
            vec![
                (-78.0, 164.0, None),
                (-20.0, 1.0, None),
                (-389.0, 2804.0, None)
            ]
        );
    }

    #[test]
    fn descriptive_text_yields_no_points() {
        for text in [
            "Various",
            "Roams the zone",
            "Need Info",
            "?",
            "Inner Sanctum",
        ] {
            assert!(
                parse_locations(text).is_empty(),
                "{text:?} should yield no points"
            );
        }
    }

    /// why: real `Npc::zone` value -- an exact target must be its own candidate
    #[test]
    fn candidate_zones_finds_a_real_exact_match() {
        let candidates = candidate_zones("Howling Stones");
        assert!(
            candidates.contains(&"Howling Stones".to_string()),
            "{candidates:?}"
        );
    }

    /// why: honest negative -- an unrelated target must not "helpfully" match
    #[test]
    fn candidate_zones_does_not_invent_a_match() {
        let candidates = candidate_zones("ZzzNotARealZoneZzz");
        assert!(candidates.is_empty(), "{candidates:?}");
    }

    #[test]
    fn markers_for_zone_returns_only_that_zones_own_npcs() {
        let markers = markers_for_zone("Howling Stones");
        assert!(
            !markers.is_empty(),
            "Howling Stones should have real parseable NPC spawns"
        );
        // why: sanity -- every marker is a real NPC name, not an empty row
        assert!(markers.iter().all(|(name, ..)| !name.is_empty()));
    }
}
