//! why: NPC bestiary, baked in like `itemdata.rs`/`monsterdata.rs`/`zonedata.rs`
//!
//! Generated by `~/eql/scrape_eqlwiki_npcs.py`. 6,532 entries, one per
//! "Named Mob" page -- distinct from `monsterdata.rs`'s narrower
//! item-scrape-sourced mob->drops lookup, no stats/location/loot detail there.

use regex::Regex;
use serde::{Deserialize, Serialize};
use std::sync::OnceLock;

const NPC_DATA_JSON: &str = include_str!("../../../packs/npcs.json");

/// why: richer than `itemdata::ItemDrop` -- from the NPC page's own drop
/// table, carries rarity/drop-chance the item scrape never has
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct KnownLoot {
    pub item: String,
    pub rarity: Option<String>,
    pub stack: Option<f64>,
    pub chance_per_kill: Option<f64>,
    pub chance_per_drop: Option<f64>,
}

/// why: presentation-ready like `zonedata::Zone` -- doubles as parse target and DTO
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Npc {
    pub id: String,
    pub name: String,
    pub url: String,
    pub race: Option<String>,
    pub class: Option<String>,
    pub level: Option<String>,
    /// why: None common for multi-zone NPCs; `location` carries those instead
    pub zone: Option<String>,
    pub location: Option<String>,
    pub respawn_time: Option<String>,
    pub aggro_radius: Option<f64>,
    pub run_speed: Option<f64>,
    #[serde(rename = "AC")]
    pub ac: Option<i64>,
    #[serde(rename = "HP")]
    pub hp: Option<i64>,
    pub hp_regen: Option<i64>,
    pub mana_regen: Option<i64>,
    pub attacks_per_round: Option<i64>,
    pub attack_speed: Option<String>,
    pub damage_per_hit: Option<String>,
    pub special: Option<String>,
    #[serde(default)]
    pub known_loot: Vec<KnownLoot>,
    pub imagefilename: Option<String>,
    #[serde(default)]
    pub images: Vec<String>,
    pub era: Option<String>,
    #[serde(default)]
    pub categories: Vec<String>,
}

#[derive(Deserialize)]
struct NpcsDoc {
    npcs: Vec<Npc>,
}

static NPCS: OnceLock<Vec<Npc>> = OnceLock::new();

/// why: every scraped NPC, parsed once; malformed data fails loud
pub fn npcs() -> &'static [Npc] {
    NPCS.get_or_init(|| {
        let doc: NpcsDoc = serde_json::from_str(NPC_DATA_JSON)
            .unwrap_or_else(|e| panic!("packs/npcs.json failed to parse: {e}"));
        doc.npcs
    })
    .as_slice()
}

/// why: O(1) known-NPC check for a hot path (checked per shared-target
/// damage event during backfill) -- raiding.rs's own find_npc does a
/// linear scan over all 6,532 entries, fine for its low-frequency
/// curated lookups, far too costly at backfill scale here. Case-folded
/// whole-string (not eqlp_session::fold_key's first-char-only scheme --
/// that's not visible outside eqlp_session, and a plain full lowercase
/// is the simpler, sufficient answer for a wiki-name identity check).
pub fn is_known_npc_name(name: &str) -> bool {
    static NAMES: OnceLock<std::collections::HashSet<String>> = OnceLock::new();
    NAMES
        .get_or_init(|| npcs().iter().map(|n| n.name.to_lowercase()).collect())
        .contains(&name.to_lowercase())
}

/// why: NPC name -> its known_loot item names, whole-string lowercased
/// key same as is_known_npc_name. Drop Watch's second drop source --
/// real gap, measured against the player's own tracked list: 2 of his 3
/// tracked items (Blood Sky Ruby via Eye of Veeshan, Golden Coffer via
/// The Spiroc Lord) have their ONLY dropper attribution here, not in
/// packs/monsters.json's own drop tables -- the two wiki scrapes cover
/// different pages and neither subsumes the other.
pub fn known_loot_for(name: &str) -> &'static [String] {
    static MAP: OnceLock<std::collections::HashMap<String, Vec<String>>> = OnceLock::new();
    MAP.get_or_init(|| {
        let mut m: std::collections::HashMap<String, Vec<String>> =
            std::collections::HashMap::new();
        for n in npcs() {
            if n.known_loot.is_empty() {
                continue;
            }
            let e = m.entry(n.name.to_lowercase()).or_default();
            for l in &n.known_loot {
                if !e.iter().any(|x| x.eq_ignore_ascii_case(&l.item)) {
                    e.push(l.item.clone());
                }
            }
        }
        m
    })
    .get(&name.to_lowercase())
    .map(Vec::as_slice)
    .unwrap_or(&[])
}

/// why: an item counts as a ZONE drop only when this many distinct NPCs
/// in the zone are attributed with it -- the first cut unioned every
/// NPC's whole table, which smeared 167 single-mob drops onto every
/// engaged Sky mob (272 "known drops" on a trash mob, caught by the
/// player: "verify individual drops for mobs arent being attributed to
/// everything in zone"). Measured on Plane of Sky: >=3 keeps the 41
/// genuinely common drops (spiroc feathers/totems, figurines) and
/// leaves every boss- and quest-specific item to its own dropper.
/// Raised from 3 to 5 trash droppers -- "a more stringent catch-all"
/// on top of the trash-only count (Spiroc Wind Totem has seven).
const MIN_ZONE_DROPPERS: usize = 5;

/// why: EQ's naming convention -- a lowercase article means a generic
/// (trash) mob; a capitalized article or none means a named one
pub fn is_trash_name(name: &str) -> bool {
    name.starts_with("a ") || name.starts_with("an ")
}

/// why: a zone's broadly-dropped pool -- items attributed to at least
/// MIN_ZONE_DROPPERS distinct NPCs in that wiki zone. zonedata's own
/// unique_items (the zone page's HEADER table) stays the other half;
/// many zones (Plane of Sky) don't have that row even though their
/// mobs' loot is attributed per NPC. Takes the RAW log zone name ("The
/// Plane of Sky"), resolved via the same `zone_matches` alias fold
/// everything else uses. Deduped case-insensitively.
pub fn zone_loot_pool(raw_zone: &str) -> &'static [String] {
    static MAP: OnceLock<std::collections::HashMap<String, Vec<String>>> = OnceLock::new();
    let map = MAP.get_or_init(|| {
        // per zone: item (lowercased) -> (display name, distinct droppers)
        let mut counts: std::collections::HashMap<
            String,
            std::collections::HashMap<String, (String, std::collections::HashSet<String>)>,
        > = std::collections::HashMap::new();
        for n in npcs() {
            let Some(zone) = &n.zone else { continue };
            // why: only TRASH droppers count toward "zone-common" -- a raid
            // zone's boss set shares its loot (Eye of Innoruuk: nine Hate
            // bosses and a chest) and read as a zone-wide drop on every
            // mob there. EQ's own convention: trash is "a rat" / "an orc",
            // a named mob is capitalized ("A very unpleasant hand") or has
            // no article at all -- its loot is its own.
            if !is_trash_name(&n.name) {
                continue;
            }
            let per_zone = counts.entry(zone.clone()).or_default();
            for l in &n.known_loot {
                let e = per_zone
                    .entry(l.item.to_lowercase())
                    .or_insert_with(|| (l.item.clone(), std::collections::HashSet::new()));
                e.1.insert(n.name.to_lowercase());
            }
        }
        counts
            .into_iter()
            .map(|(zone, items)| {
                let broad: Vec<String> = items
                    .into_values()
                    .filter(|(_, droppers)| droppers.len() >= MIN_ZONE_DROPPERS)
                    .map(|(name, _)| name)
                    .collect();
                (zone, broad)
            })
            .collect()
    });
    map.iter()
        .find(|(k, _)| crate::zone::zone_matches(raw_zone, k))
        .map(|(_, v)| v.as_slice())
        .unwrap_or(&[])
}

/// why: every item some NPC page in this wiki zone attributes to itself
/// (lowercased). The zone page's header table lists every notable
/// item in the zone, per-mob rares included -- applied zone-wide, a
/// robe one named ghoul drops alerted on every frog in Lower Guk
/// ("attributed zone wide instead of the singular mob"). An item with
/// a known dropper in the zone belongs to that dropper; only the
/// genuinely unattributed rest of the header table stays zone-wide.
pub fn zone_attributed_items(raw_zone: &str) -> &'static std::collections::HashSet<String> {
    static MAP: OnceLock<std::collections::HashMap<String, std::collections::HashSet<String>>> =
        OnceLock::new();
    static EMPTY: OnceLock<std::collections::HashSet<String>> = OnceLock::new();
    let map = MAP.get_or_init(|| {
        let mut m: std::collections::HashMap<String, std::collections::HashSet<String>> =
            std::collections::HashMap::new();
        for n in npcs() {
            let Some(zone) = &n.zone else { continue };
            let e = m.entry(zone.clone()).or_default();
            for l in &n.known_loot {
                e.insert(l.item.to_lowercase());
            }
        }
        m
    });
    map.iter()
        .find(|(k, _)| crate::zone::zone_matches(raw_zone, k))
        .map(|(_, v)| v)
        .unwrap_or_else(|| EMPTY.get_or_init(Default::default))
}

/// why: parses free-text spawn notation into real points; descriptive
/// text ("Various", "Need Info") yields none. `%` weighting dropped --
/// multiple spawns render as multiple equal markers.
pub fn parse_locations(location: &str) -> Vec<(f32, f32, Option<f32>)> {
    static RE: OnceLock<Regex> = OnceLock::new();
    let re = RE.get_or_init(|| {
        Regex::new(r"\(?(-?\d+(?:\.\d+)?),\s*(-?\d+(?:\.\d+)?)(?:,\s*(-?\d+(?:\.\d+)?))?\)?")
            .unwrap()
    });
    // why: the wiki's newer infobox shape, "X: -257 Y: -132 Z: -99"
    // (labels, no commas) -- folded to the tuple shape the one regex reads
    static XYZ: OnceLock<Regex> = OnceLock::new();
    let xyz = XYZ.get_or_init(|| {
        Regex::new(
            r"(?i)X:\s*(-?\d+(?:\.\d+)?)\s*Y:\s*(-?\d+(?:\.\d+)?)(?:\s*Z:\s*(-?\d+(?:\.\d+)?))?",
        )
        .unwrap()
    });
    let folded = xyz.replace_all(location, |c: &regex::Captures| match c.get(3) {
        Some(z) => format!("({}, {}, {})", &c[1], &c[2], z.as_str()),
        None => format!("({}, {})", &c[1], &c[2]),
    });
    re.captures_iter(&folded)
        .filter_map(|c| {
            let x: f32 = c.get(1)?.as_str().parse().ok()?;
            let y: f32 = c.get(2)?.as_str().parse().ok()?;
            let z: Option<f32> = c.get(3).and_then(|m| m.as_str().parse().ok());
            Some((x, y, z))
        })
        .collect()
}

/// why: loosely resembles `target`, deliberately broad -- wiki names and
/// EQ shortcodes have no derivable relationship, so surfaced as
/// toggle-able candidates rather than auto-applied
pub fn candidate_zones(target: &str) -> Vec<String> {
    fn norm(s: &str) -> String {
        s.chars()
            .filter(|c| c.is_ascii_alphanumeric())
            .map(|c| c.to_ascii_lowercase())
            .collect()
    }
    let t = norm(target);
    if t.is_empty() {
        return Vec::new();
    }
    let mut candidates: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    // why: who_name FIRST -- the zones pack's own stem<->display bridge.
    // Containment alone can't span abbreviated stems: "newsebexp" vs
    // "New Sebilis Expedition" shares no substring either way, and that
    // zone (reported live) listed zero NPCs. A stem matching a zone's
    // who_name adopts that zone's display name as a candidate, then the
    // display name ALSO runs through the containment fold below, since
    // wiki NPC zone strings sometimes vary from zones.json's own name.
    let mut folds: Vec<String> = vec![t.clone()];
    for z in crate::zonedata::zones() {
        let Some(who) = &z.who_name else { continue };
        if crate::zonedata::map_shortnames(who)
            .iter()
            .any(|s| norm(s) == t)
        {
            candidates.insert(z.name.clone());
            folds.push(norm(&z.name));
        }
    }
    for n in npcs() {
        let Some(z) = &n.zone else { continue };
        let nz = norm(z);
        if nz.is_empty() {
            continue;
        }
        if folds.iter().any(|f| nz.contains(f) || f.contains(&nz)) {
            candidates.insert(z.clone());
        }
    }
    candidates.into_iter().collect()
}

/// why: "navigate to this NPC" -- every spawn point for one wiki NPC,
/// (zone, x, y, z) per parsed coordinate; multi-zone NPCs (zone None)
/// have no single place to route to and contribute nothing
pub fn nav_points_for(name: &str) -> Vec<(String, f32, f32, Option<f32>)> {
    let mut out = Vec::new();
    // why: surveyed points first -- they carry a z (see spawndata); the
    // zone is the wiki zone the raw log zone folds to, so routing keys
    // stay the ones zone_matches already resolves everywhere else
    for s in crate::spawndata::spawns() {
        if !crate::spawndata::same_mob(&s.name, name) {
            continue;
        }
        let zone = crate::zonedata::zones()
            .iter()
            .find(|z| crate::zone::zone_matches(&s.zone, &z.name))
            .map(|z| z.name.clone())
            .unwrap_or_else(|| s.zone.clone());
        out.push((zone, s.x, s.y, Some(s.z)));
    }
    for n in npcs() {
        if !n.name.eq_ignore_ascii_case(name) {
            continue;
        }
        let (Some(zone), Some(loc)) = (&n.zone, &n.location) else {
            continue;
        };
        for (x, y, z) in parse_locations(loc) {
            // why: a wiki spot a survey point already covers is dropped --
            // one marker, the one with a z
            if out.iter().any(|(oz, ox, oy, _)| {
                oz == zone && ((ox - x).powi(2) + (oy - y).powi(2)).sqrt() <= SURVEY_COVERS_UNITS
            }) {
                continue;
            }
            out.push((zone.clone(), x, y, z));
        }
    }
    out
}

/// why: a wiki spot this close to a surveyed point is the same spawn
const SURVEY_COVERS_UNITS: f32 = 15.0;

/// why: exact match -- fuzzy work already happened in `candidate_zones`;
/// multi-spawn mobs contribute one marker per point, not deduplicated
pub fn markers_for_zone(zone: &str) -> Vec<(String, f32, f32, Option<f32>)> {
    markers_for_zone_sourced(zone)
        .into_iter()
        .map(|m| (m.name, m.x, m.y, m.z))
        .collect()
}

/// why: one plotted spot with everything the map colors and labels by
#[derive(Debug, Clone)]
pub struct SourcedMarker {
    pub name: String,
    /// why: /loc coordinates (wiki spots and the survey alike); the
    /// viewer maps them into map-file space
    pub x: f32,
    pub y: f32,
    pub z: Option<f32>,
    /// why: "survey" (the in-game /loc pack, 3D) or "wiki" (XY only)
    pub source: &'static str,
    /// why: the wiki's level string ("37-39"), for con coloring
    pub level: Option<String>,
}

/// why: markers with their source -- "survey" (the in-game /loc pack,
/// has a z) or "wiki" (XY only) -- so the map can color them apart.
/// Survey points come first and cover any wiki spot within
/// SURVEY_COVERS_UNITS of them.
pub fn markers_for_zone_sourced(zone: &str) -> Vec<SourcedMarker> {
    let mut out: Vec<SourcedMarker> = Vec::new();
    for s in crate::spawndata::spawns_in_wiki_zone(zone) {
        // why: the wiki's own name and level for the mob when it has a
        // page, so the marker, its con color and the NPC list agree
        let page = npcs().iter().find(|n| {
            n.zone.as_deref() == Some(zone) && crate::spawndata::same_mob(&n.name, &s.name)
        });
        out.push(SourcedMarker {
            name: page
                .map(|n| n.name.clone())
                .unwrap_or_else(|| s.name.clone()),
            x: s.x,
            y: s.y,
            z: Some(s.z),
            source: "survey",
            level: page.and_then(|n| n.level.clone()),
        });
    }
    for n in npcs() {
        if n.zone.as_deref() != Some(zone) {
            continue;
        }
        let Some(loc) = &n.location else { continue };
        for (x, y, z) in parse_locations(loc) {
            if out.iter().any(|m| {
                m.source == "survey"
                    && ((m.x - x).powi(2) + (m.y - y).powi(2)).sqrt() <= SURVEY_COVERS_UNITS
            }) {
                continue;
            }
            out.push(SourcedMarker {
                name: n.name.clone(),
                x,
                y,
                z,
                source: "wiki",
                level: n.level.clone(),
            });
        }
    }
    out
}

#[cfg(test)]
mod location_tests {
    use super::*;

    /// why: real breadth data, Plane of Sky -- Spiroc Wind Totem has 7
    /// attributed droppers (zone-common), Golden Coffer exactly one (The
    /// Spiroc Lord); the pool must carry the first and never the second
    #[test]
    fn zone_pool_is_breadth_gated() {
        let pool = zone_loot_pool("The Plane of Sky");
        assert!(pool.iter().any(|i| i == "Spiroc Wind Totem"));
        assert!(!pool.iter().any(|i| i == "Golden Coffer"));
        assert!(!pool.iter().any(|i| i == "Blood Sky Ruby"));
    }

    /// why: "everything in Plane of Hate is marked to drop Eye of
    /// Innoruuk and Hand of Maestro" -- ten droppers, all bosses and a
    /// chest; three droppers, all named. Named mobs don't make an item common.
    #[test]
    fn a_boss_set_sharing_an_item_does_not_make_it_zone_common() {
        let pool = zone_loot_pool("Plane of Hate");
        assert!(!pool.iter().any(|i| i == "Eye of Innoruuk"), "got {pool:?}");
        assert!(!pool.iter().any(|i| i == "Hand of the Maestro"));
        assert!(is_trash_name("a repulsive rat"));
        assert!(!is_trash_name("A very unpleasant hand"));
        assert!(!is_trash_name("Maestro of Rancor"));
    }

    /// why: real npcs.json entries -- Eye of Veeshan has one exact 3D
    /// spawn point; Gorgalosk's location is prose ("3rd Island"), no
    /// coordinates, so it must contribute nothing rather than a junk point
    /// why: the shape from a current wiki page, pasted by the player:
    /// "Location: X: -257 Y: -132 Z: -99" -- labels, line breaks, no commas
    #[test]
    fn labeled_xyz_location_parses_with_its_z() {
        assert_eq!(
            parse_locations("X: -257\n\nY: -132 Z: -99"),
            vec![(-257.0, -132.0, Some(-99.0))]
        );
        assert_eq!(parse_locations("X: 12 Y: 34"), vec![(12.0, 34.0, None)]);
    }

    #[test]
    fn nav_points_come_from_real_coordinates_only() {
        let eye = nav_points_for("Eye of Veeshan");
        assert_eq!(
            eye,
            vec![("Plane of Sky".to_string(), -267.0, -1370.0, Some(1250.0))]
        );
        assert!(nav_points_for("Gorgalosk").is_empty());
    }

    /// why: multi-spawn mob, real entry -- one point per coordinate pair
    #[test]
    fn a_multi_spawn_npc_yields_every_point() {
        let pts = nav_points_for("Guard Zintrin");
        assert_eq!(pts.len(), 2);
        assert!(pts.iter().all(|(z, _, _, _)| z == "East Freeport"));
    }

    /// why: real strings pulled straight from packs/npcs.json
    #[test]
    fn parses_every_real_shape_seen_in_the_scrape() {
        assert_eq!(
            parse_locations("(836, -2879)"),
            vec![(836.0, -2879.0, None)]
        );
        assert_eq!(
            parse_locations("25% @ (55, -573)"),
            vec![(55.0, -573.0, None)]
        );
        assert_eq!(
            parse_locations("-59.93, 433.90, 9.75"),
            vec![(-59.93, 433.90, Some(9.75))]
        );
        assert_eq!(
            parse_locations("(667, 146, -51.59)"),
            vec![(667.0, 146.0, Some(-51.59))]
        );
        assert_eq!(parse_locations("1182, -834"), vec![(1182.0, -834.0, None)]);

        let multi = parse_locations("8% @ (-78, 164), 8% @ (-20, 1), 8% @ (-389, 2804)");
        assert_eq!(
            multi,
            vec![
                (-78.0, 164.0, None),
                (-20.0, 1.0, None),
                (-389.0, 2804.0, None)
            ]
        );
    }

    #[test]
    fn descriptive_text_yields_no_points() {
        for text in [
            "Various",
            "Roams the zone",
            "Need Info",
            "?",
            "Inner Sanctum",
        ] {
            assert!(
                parse_locations(text).is_empty(),
                "{text:?} should yield no points"
            );
        }
    }

    /// why: real `Npc::zone` value -- an exact target must be its own candidate
    #[test]
    fn candidate_zones_finds_a_real_exact_match() {
        let candidates = candidate_zones("Howling Stones");
        assert!(
            candidates.contains(&"Howling Stones".to_string()),
            "{candidates:?}"
        );
    }

    /// why: honest negative -- an unrelated target must not "helpfully" match
    #[test]
    fn candidate_zones_does_not_invent_a_match() {
        let candidates = candidate_zones("ZzzNotARealZoneZzz");
        assert!(candidates.is_empty(), "{candidates:?}");
    }

    #[test]
    fn markers_for_zone_returns_only_that_zones_own_npcs() {
        let markers = markers_for_zone("Howling Stones");
        assert!(
            !markers.is_empty(),
            "Howling Stones should have real parseable NPC spawns"
        );
        // why: sanity -- every marker is a real NPC name, not an empty row
        assert!(markers.iter().all(|(name, ..)| !name.is_empty()));
    }
}

#[cfg(test)]
mod candidate_zone_tests {
    use super::*;

    /// why: reported live -- the "newsebexp" map stem shares no
    /// substring with "New Sebilis Expedition", so the containment-only
    /// matcher listed zero NPCs for the whole zone; who_name is the
    /// bridge
    #[test]
    fn an_abbreviated_map_stem_resolves_through_who_name() {
        let c = candidate_zones("newsebexp");
        assert!(c.iter().any(|z| z == "New Sebilis Expedition"), "got {c:?}");
    }

    /// why: the plain containment path still stands for stems that ARE
    /// substrings of their wiki zone name
    #[test]
    fn a_plain_stem_still_matches_by_containment() {
        let c = candidate_zones("blackburrow");
        assert!(c.iter().any(|z| z == "Blackburrow"), "got {c:?}");
    }
}
