//! Wires the scraped NPC bestiary (`packs/npcs.json`) into the live app --
//! the Game Data module's NPC tab, same `include_str!`-at-compile-time
//! pattern `itemdata.rs`/`monsterdata.rs`/`zonedata.rs` already use.
//!
//! `packs/npcs.json` is generated by `~/eql/scrape_eqlwiki_npcs.py`, not
//! hand-written -- re-run it and re-copy the output here to pick up wiki
//! changes. 6,532 entries, one per "Named Mob" page the wiki carries (see
//! that script's own `skipped_not_namedmobpage` count for what it left
//! out) -- distinct from `monsterdata.rs`'s much narrower mob -> drops
//! lookup, which only ever covers a mob the *item* scrape happened to name
//! as a drop source, and carries no NPC stats/location/loot-table detail
//! at all.

use regex::Regex;
use serde::{Deserialize, Serialize};
use std::sync::OnceLock;

const NPC_DATA_JSON: &str = include_str!("../../../packs/npcs.json");

/// One entry in an NPC's own known-loot table -- richer than
/// `itemdata::ItemDrop` (which only ever names the mob, from the *item*
/// page's side), since this comes from the *NPC* page's own drop table:
/// rarity and drop-chance figures the item scrape never carries.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct KnownLoot {
    pub item: String,
    pub rarity: Option<String>,
    pub stack: Option<f64>,
    pub chance_per_kill: Option<f64>,
    pub chance_per_drop: Option<f64>,
}

/// One NPC, as scraped -- already presentation-ready, so (like
/// `zonedata::Zone`) this struct doubles as both the parse target and the
/// DTO `commands::list_npcs` sends over IPC.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Npc {
    pub id: String,
    pub name: String,
    pub url: String,
    pub race: Option<String>,
    pub class: Option<String>,
    pub level: Option<String>,
    /// The zone this NPC's own infobox names, when the wiki page states
    /// one plainly. `None` is common for NPCs that show up in several
    /// zones (a placeholder/boat/generic-name page) -- `location` below is
    /// what those carry instead, as unstructured wikitext, not a second
    /// clean field to fall back to automatically.
    pub zone: Option<String>,
    pub location: Option<String>,
    pub respawn_time: Option<String>,
    pub aggro_radius: Option<f64>,
    pub run_speed: Option<f64>,
    #[serde(rename = "AC")]
    pub ac: Option<i64>,
    #[serde(rename = "HP")]
    pub hp: Option<i64>,
    pub hp_regen: Option<i64>,
    pub mana_regen: Option<i64>,
    pub attacks_per_round: Option<i64>,
    pub attack_speed: Option<String>,
    pub damage_per_hit: Option<String>,
    pub special: Option<String>,
    #[serde(default)]
    pub known_loot: Vec<KnownLoot>,
    pub imagefilename: Option<String>,
    #[serde(default)]
    pub images: Vec<String>,
    pub era: Option<String>,
    #[serde(default)]
    pub categories: Vec<String>,
}

#[derive(Deserialize)]
struct NpcsDoc {
    npcs: Vec<Npc>,
}

static NPCS: OnceLock<Vec<Npc>> = OnceLock::new();

/// Every NPC the scrape carries. Parses the embedded JSON once, on first
/// use -- a malformed embedded file is a build-time data bug, same stance
/// every other `packs/*.json` loader in this crate takes.
pub fn npcs() -> &'static [Npc] {
    NPCS.get_or_init(|| {
        let doc: NpcsDoc = serde_json::from_str(NPC_DATA_JSON)
            .unwrap_or_else(|e| panic!("packs/npcs.json failed to parse: {e}"));
        doc.npcs
    })
    .as_slice()
}

/// Parses `Npc::location`'s free-text spawn notation into every real
/// point it names -- confirmed real shapes in the scrape: `"(X, Y)"`,
/// `"N% @ (X, Y)"`, a comma-separated list of the latter for a mob with
/// several possible spawns, sometimes a third Z value (`"(X, Y, Z)"`),
/// sometimes with no parentheses at all (`"X, Y, Z"`). Purely descriptive
/// text ("Various", "Roams the zone", "Need Info", a Talk-page reference)
/// yields no points -- this only ever extracts real numbers, never
/// invents a position out of prose. `%` weighting is deliberately
/// dropped, not carried through -- multiple spawn points render as
/// multiple equal markers, not a probability display this app doesn't
/// have a use for yet.
pub fn parse_locations(location: &str) -> Vec<(f32, f32, Option<f32>)> {
    static RE: OnceLock<Regex> = OnceLock::new();
    let re = RE.get_or_init(|| {
        Regex::new(r"\(?(-?\d+(?:\.\d+)?),\s*(-?\d+(?:\.\d+)?)(?:,\s*(-?\d+(?:\.\d+)?))?\)?").unwrap()
    });
    re.captures_iter(location)
        .filter_map(|c| {
            let x: f32 = c.get(1)?.as_str().parse().ok()?;
            let y: f32 = c.get(2)?.as_str().parse().ok()?;
            let z: Option<f32> = c.get(3).and_then(|m| m.as_str().parse().ok());
            Some((x, y, z))
        })
        .collect()
}

/// Every distinct `Npc::zone` value whose normalized form loosely
/// resembles `target` (typically a map file's own display name, e.g.
/// "Befallen") -- deliberately broad: the wiki's zone display names
/// ("East Freeport") and the map format's internal EQ shortcodes
/// ("freporte") don't share a derivable relationship for most zones, so
/// there's no way to build a precise matcher without a hand-curated
/// alias table. Instead, candidates are surfaced to the user as
/// toggle-able options (see `commands::list_npc_zone_candidates`) rather
/// than auto-applied -- a false-positive candidate just means one extra
/// toggle the user leaves off after glancing at the map; a missed real
/// match means no candidate shown for a zone this app can't confidently
/// name-match, not a wrong guess presented as fact. Either way, nothing
/// here silently mislabels data.
pub fn candidate_zones(target: &str) -> Vec<String> {
    fn norm(s: &str) -> String {
        s.chars().filter(|c| c.is_ascii_alphanumeric()).map(|c| c.to_ascii_lowercase()).collect()
    }
    let t = norm(target);
    if t.is_empty() {
        return Vec::new();
    }
    let mut candidates: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    for n in npcs() {
        let Some(z) = &n.zone else { continue };
        let nz = norm(z);
        if !nz.is_empty() && (nz.contains(&t) || t.contains(&nz)) {
            candidates.insert(z.clone());
        }
    }
    candidates.into_iter().collect()
}

/// Every real spawn point for NPCs whose `zone` field is exactly `zone`
/// (an exact match -- the fuzzy work already happened in
/// `candidate_zones`, and by the time this is called the frontend has
/// already resolved one specific real `Npc::zone` value from that
/// candidate list). A mob with several possible spawns contributes one
/// marker per point, same name repeated -- not deduplicated, the same way
/// a map file's own `P` markers aren't.
pub fn markers_for_zone(zone: &str) -> Vec<(String, f32, f32, Option<f32>)> {
    let mut out = Vec::new();
    for n in npcs() {
        if n.zone.as_deref() != Some(zone) {
            continue;
        }
        let Some(loc) = &n.location else { continue };
        for (x, y, z) in parse_locations(loc) {
            out.push((n.name.clone(), x, y, z));
        }
    }
    out
}

#[cfg(test)]
mod location_tests {
    use super::*;

    /// Real strings pulled straight from packs/npcs.json.
    #[test]
    fn parses_every_real_shape_seen_in_the_scrape() {
        assert_eq!(parse_locations("(836, -2879)"), vec![(836.0, -2879.0, None)]);
        assert_eq!(parse_locations("25% @ (55, -573)"), vec![(55.0, -573.0, None)]);
        assert_eq!(
            parse_locations("-59.93, 433.90, 9.75"),
            vec![(-59.93, 433.90, Some(9.75))]
        );
        assert_eq!(parse_locations("(667, 146, -51.59)"), vec![(667.0, 146.0, Some(-51.59))]);
        assert_eq!(parse_locations("1182, -834"), vec![(1182.0, -834.0, None)]);

        let multi = parse_locations("8% @ (-78, 164), 8% @ (-20, 1), 8% @ (-389, 2804)");
        assert_eq!(multi, vec![(-78.0, 164.0, None), (-20.0, 1.0, None), (-389.0, 2804.0, None)]);
    }

    #[test]
    fn descriptive_text_yields_no_points() {
        for text in ["Various", "Roams the zone", "Need Info", "?", "Inner Sanctum"] {
            assert!(parse_locations(text).is_empty(), "{text:?} should yield no points");
        }
    }

    /// Real data: "Howling Stones" is a real `Npc::zone` value in
    /// packs/npcs.json (confirmed against the real scrape) -- an exact
    /// target should always be its own candidate.
    #[test]
    fn candidate_zones_finds_a_real_exact_match() {
        let candidates = candidate_zones("Howling Stones");
        assert!(candidates.contains(&"Howling Stones".to_string()), "{candidates:?}");
    }

    /// The honest negative: no derivable relationship between "East
    /// Freeport" and any single-word map-file-style target, so a
    /// deliberately unrelated target must not "helpfully" match it.
    #[test]
    fn candidate_zones_does_not_invent_a_match() {
        let candidates = candidate_zones("ZzzNotARealZoneZzz");
        assert!(candidates.is_empty(), "{candidates:?}");
    }

    #[test]
    fn markers_for_zone_returns_only_that_zones_own_npcs() {
        let markers = markers_for_zone("Howling Stones");
        assert!(!markers.is_empty(), "Howling Stones should have real parseable NPC spawns");
        // Sanity: every returned marker really is a real NPC name, not an
        // empty/garbage row.
        assert!(markers.iter().all(|(name, ..)| !name.is_empty()));
    }
}
