//! why: spell catalog, baked in at compile time like `itemdata.rs`
//!
//! Generated by `~/eql/scrape_eqlwiki_spells.py`. 1928 spells shipped
//! whole -- feeds Game Data's Spells tab and Spellbook's Known/Possible join.

use serde::{Deserialize, Serialize};
use std::sync::OnceLock;

const SPELL_DATA_JSON: &str = include_str!("../../../packs/spells.json");

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SpellClass {
    pub class: String,
    /// why: None where the wiki cell was blank -- 17 of 2019 pairs
    pub level: Option<u32>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SpellSlot {
    pub slot: u32,
    /// why: raw wiki cell text, unparsed; `description` is what the app shows
    pub effect: String,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Spell {
    pub id: String,
    pub name: String,
    pub url: Option<String>,
    pub description: Option<String>,
    #[serde(default)]
    pub classes: Vec<SpellClass>,
    pub skill: Option<String>,
    pub mana: Option<f64>,
    pub range: Option<f64>,
    pub casting_time: Option<f64>,
    pub fizzle_time: Option<f64>,
    pub recast_time: Option<f64>,
    pub duration: Option<String>,
    pub target_type: Option<String>,
    pub spell_type: Option<String>,
    pub resist: Option<String>,
    pub msg_cast_on_you: Option<String>,
    pub msg_cast_on_other: Option<String>,
    pub msg_wears_off: Option<String>,
    #[serde(default)]
    pub slots: Vec<SpellSlot>,
    #[serde(default)]
    pub items_with_effect: Vec<String>,
    pub where_to_obtain: Option<String>,
    pub era: Option<String>,
    #[serde(default)]
    pub categories: Vec<String>,
    pub icon: Option<String>,
}

#[derive(Debug, Deserialize)]
struct SpellsDoc {
    spells: Vec<Spell>,
}

static SPELLS: OnceLock<Vec<Spell>> = OnceLock::new();

/// why: every scraped spell, parsed once; malformed data fails loud
pub fn spells() -> &'static [Spell] {
    SPELLS
        .get_or_init(|| {
            let doc: SpellsDoc = serde_json::from_str(SPELL_DATA_JSON)
                .unwrap_or_else(|e| panic!("packs/spells.json failed to parse: {e}"));
            doc.spells
        })
        .as_slice()
}

/// why: catalog lookup by exact name; linear scan, not a hot path
pub fn spell_by_name(name: &str) -> Option<&'static Spell> {
    spells().iter().find(|s| s.name == name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loads_the_real_catalog() {
        assert_eq!(spells().len(), 1928);
        let s = spell_by_name("Fire Bolt").expect("Fire Bolt should be in the catalog");
        assert_eq!(s.mana, Some(28.0));
        assert_eq!(s.casting_time, Some(2.0));
    }

    #[test]
    fn unknown_name_is_none_not_a_panic() {
        assert!(spell_by_name("Not A Real Spell").is_none());
    }
}
