//! why: spell catalog, baked in at compile time like `itemdata.rs`
//!
//! Generated by `~/eql/scrape_eqlwiki_spells.py`. 1928 spells shipped
//! whole -- feeds Game Data's Spells tab and Spellbook's Known/Possible join.

use serde::{Deserialize, Serialize};
use std::sync::OnceLock;

const SPELL_DATA_JSON: &str = include_str!("../../../packs/spells.json");

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SpellClass {
    pub class: String,
    /// why: None where the wiki cell was blank -- 17 of 2019 pairs
    pub level: Option<u32>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SpellSlot {
    pub slot: u32,
    /// why: raw wiki cell text, unparsed; `description` is what the app shows
    pub effect: String,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Spell {
    pub id: String,
    pub name: String,
    pub url: Option<String>,
    pub description: Option<String>,
    #[serde(default)]
    pub classes: Vec<SpellClass>,
    pub skill: Option<String>,
    pub mana: Option<f64>,
    pub range: Option<f64>,
    pub casting_time: Option<f64>,
    pub fizzle_time: Option<f64>,
    pub recast_time: Option<f64>,
    pub duration: Option<String>,
    pub target_type: Option<String>,
    pub spell_type: Option<String>,
    pub resist: Option<String>,
    pub msg_cast_on_you: Option<String>,
    pub msg_cast_on_other: Option<String>,
    pub msg_wears_off: Option<String>,
    #[serde(default)]
    pub slots: Vec<SpellSlot>,
    #[serde(default)]
    pub items_with_effect: Vec<String>,
    pub where_to_obtain: Option<String>,
    pub era: Option<String>,
    #[serde(default)]
    pub categories: Vec<String>,
    pub icon: Option<String>,
}

#[derive(Debug, Deserialize)]
struct SpellsDoc {
    spells: Vec<Spell>,
}

static SPELLS: OnceLock<Vec<Spell>> = OnceLock::new();

/// why: every scraped spell, parsed once; malformed data fails loud
pub fn spells() -> &'static [Spell] {
    SPELLS
        .get_or_init(|| {
            let doc: SpellsDoc = serde_json::from_str(SPELL_DATA_JSON)
                .unwrap_or_else(|e| panic!("packs/spells.json failed to parse: {e}"));
            doc.spells
        })
        .as_slice()
}

static SPELLS_BY_NAME: OnceLock<std::collections::HashMap<&'static str, &'static Spell>> =
    OnceLock::new();

/// why: real regression, caught live -- this used to be a genuine linear
/// scan ("not a hot path" was true for every caller at the time), until
/// ingest.rs's own attribute_effect started calling it per real landing
/// line during backfill, turning a 1928-entry scan into the actual
/// bottleneck (measured: backfill on a real 2.9M-line log went 3.5s ->
/// 7.5s). Same first-match-wins semantics as the old `.find()` -- 2 real
/// duplicate-named entries exist in the scrape (different ranks sharing
/// a display name), `or_insert` keeps whichever comes first in the
/// catalog's own order, same as `.find()` always did.
pub fn spell_by_name(name: &str) -> Option<&'static Spell> {
    SPELLS_BY_NAME
        .get_or_init(|| {
            // why: a display name can belong to two wiki pages (real, 2026-09-03
            // re-scrape: the `Full_Heal` page is titled "Healing" alongside the
            // `Healing` page itself) -- the page whose own slug IS the name is
            // the canonical one and wins; otherwise first in catalog order
            let mut m: std::collections::HashMap<&'static str, &'static Spell> =
                std::collections::HashMap::new();
            for s in spells() {
                let slug = s.name.replace(' ', "_");
                let canonical = s.id.eq_ignore_ascii_case(&slug)
                    || s.url.as_deref().is_some_and(|u| {
                        u.rsplit('/')
                            .next()
                            .is_some_and(|t| t.eq_ignore_ascii_case(&slug))
                    });
                match m.get(s.name.as_str()) {
                    Some(_) if !canonical => {}
                    _ => {
                        m.insert(s.name.as_str(), s);
                    }
                }
            }
            m
        })
        .get(name)
        .copied()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loads_the_real_catalog() {
        assert_eq!(spells().len(), 2010);
        let s = spell_by_name("Fire Bolt").expect("Fire Bolt should be in the catalog");
        assert_eq!(s.mana, Some(28.0));
        assert_eq!(s.casting_time, Some(2.0));
    }

    /// why: real collision -- two pages titled "Healing"; the Healing
    /// page (2.5s cast, "You feel much better.") is the spell, Full_Heal
    /// is a renamed page that must not shadow it
    #[test]
    fn a_display_name_shared_by_two_pages_resolves_to_the_canonical_page() {
        let s = spell_by_name("Healing").expect("in catalog");
        assert_eq!(s.id, "Healing");
        assert_eq!(s.casting_time, Some(2.5));
    }

    #[test]
    fn unknown_name_is_none_not_a_panic() {
        assert!(spell_by_name("Not A Real Spell").is_none());
    }

    /// why: real duplicate in the scrape -- 2 "Greater Healing" entries
    /// (different ranks, same display name) -- the cached index must
    /// still pick one consistently (first in catalog order), same
    /// first-match-wins semantics the old linear `.find()` always had
    #[test]
    fn a_real_duplicate_name_still_resolves_to_one_consistent_entry() {
        let a = spell_by_name("Greater Healing").expect("real duplicate name");
        let b = spell_by_name("Greater Healing").expect("real duplicate name");
        assert_eq!(
            a.casting_time, b.casting_time,
            "same cached entry both times"
        );
    }
}
