//! Wires the scraped spell catalog (`packs/spells.json`) into the live
//! app -- same `include_str!`-at-compile-time pattern `itemdata.rs`/
//! `aadata.rs`/`npcdata.rs`/`zonedata.rs` already use.
//!
//! `packs/spells.json` is generated by `~/eql/scrape_eqlwiki_spells.py`,
//! not hand-written -- re-run it and re-copy the output here to pick up
//! wiki changes. 1928 spells, shipped whole (no filtering/paging) the same
//! way `zonedata::zones`/`npcdata::npcs` are -- the Game Data module's own
//! Spells tab, and what `ingest::SpellLog`'s Known/Possible names join
//! against for the Character module's Spellbook subpage (casting time,
//! mana cost, description/damage text, ...) -- see that module's own doc
//! for exactly what "Known" vs "Possible" means.

use serde::{Deserialize, Serialize};
use std::sync::OnceLock;

const SPELL_DATA_JSON: &str = include_str!("../../../packs/spells.json");

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SpellClass {
    pub class: String,
    /// `None` for a handful of real scrape rows where the wiki table cell
    /// itself was blank -- 17 of 2019 class/level pairs, checked directly
    /// against `spells.json`, not assumed.
    pub level: Option<u32>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SpellSlot {
    pub slot: u32,
    /// Raw wiki cell text, e.g. "Decrease Hitpoints by 65" -- not parsed
    /// into a number here. `description` usually restates the same effect
    /// in prose (Fire Bolt: "causing 65 damage") and is what this app
    /// actually shows; `slots` is kept for whenever a structured read of
    /// the mechanical effect turns out to be worth building.
    pub effect: String,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Spell {
    pub id: String,
    pub name: String,
    pub url: Option<String>,
    pub description: Option<String>,
    #[serde(default)]
    pub classes: Vec<SpellClass>,
    pub skill: Option<String>,
    pub mana: Option<f64>,
    pub range: Option<f64>,
    pub casting_time: Option<f64>,
    pub fizzle_time: Option<f64>,
    pub recast_time: Option<f64>,
    pub duration: Option<String>,
    pub target_type: Option<String>,
    pub spell_type: Option<String>,
    pub resist: Option<String>,
    pub msg_cast_on_you: Option<String>,
    pub msg_cast_on_other: Option<String>,
    pub msg_wears_off: Option<String>,
    #[serde(default)]
    pub slots: Vec<SpellSlot>,
    #[serde(default)]
    pub items_with_effect: Vec<String>,
    pub where_to_obtain: Option<String>,
    pub era: Option<String>,
    #[serde(default)]
    pub categories: Vec<String>,
    pub icon: Option<String>,
}

#[derive(Debug, Deserialize)]
struct SpellsDoc {
    spells: Vec<Spell>,
}

static SPELLS: OnceLock<Vec<Spell>> = OnceLock::new();

/// Every spell the scrape carries. Parses the embedded JSON once, on
/// first use -- a malformed embedded file is a build-time data bug, loud
/// and immediate, same stance `itemdata::items` takes on its own pack.
pub fn spells() -> &'static [Spell] {
    SPELLS
        .get_or_init(|| {
            let doc: SpellsDoc = serde_json::from_str(SPELL_DATA_JSON)
                .unwrap_or_else(|e| panic!("packs/spells.json failed to parse: {e}"));
            doc.spells
        })
        .as_slice()
}

/// Catalog lookup by the exact name a log line carries -- `None` for a
/// spell the scrape doesn't have (a homebrew/custom spell this fork
/// added that the wiki hasn't documented yet, or a name mismatch), not an
/// error. Linear scan: 1928 entries, called per spellbook row on an
/// already-infrequent page open, not a hot path worth indexing for.
pub fn spell_by_name(name: &str) -> Option<&'static Spell> {
    spells().iter().find(|s| s.name == name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loads_the_real_catalog() {
        assert_eq!(spells().len(), 1928);
        let s = spell_by_name("Fire Bolt").expect("Fire Bolt should be in the catalog");
        assert_eq!(s.mana, Some(28.0));
        assert_eq!(s.casting_time, Some(2.0));
    }

    #[test]
    fn unknown_name_is_none_not_a_panic() {
        assert!(spell_by_name("Not A Real Spell").is_none());
    }
}
