//! why: spell -> stacking group id, baked in at compile time like `classdata.rs`
//!
//! Generated by `~/eql/build_spell_stacking.py` from the game client's own
//! `spells_us.txt` (numeric spell id -> name) joined against
//! `Resources/SpellStackingGroups.txt` (id -> group) -- two spells sharing
//! a group can't both be usefully active, the newer/higher one wins. Only
//! 48 entries: `spells_us.txt` is the legacy classic-EQ spell table, so it
//! only covers spells that carried over from classic content by name
//! (poison/disease DoT lines, familiars, Levitate). This app's own newer
//! spells (illusions, Ice Comet, Yaulp variants) never had a classic id at
//! all, so they get no entry -- `ui/src/lib/character/spellSuggest.ts`'s
//! own lineKey/isIllusion heuristics still carry those; this is a real,
//! authoritative supplement for the subset it does cover, not a replacement.

use std::collections::HashMap;
use std::sync::OnceLock;

const STACKING_DATA_JSON: &str = include_str!("../../../packs/spell_stacking.json");

static STACKING_DATA: OnceLock<HashMap<String, u32>> = OnceLock::new();

/// why: every catalog spell with a real stacking-group entry
pub fn stacking_groups() -> &'static HashMap<String, u32> {
    STACKING_DATA.get_or_init(|| {
        serde_json::from_str(STACKING_DATA_JSON).unwrap_or_else(|e| {
            // why: malformed embedded data is a build bug, fail loud
            panic!("packs/spell_stacking.json failed to parse: {e}")
        })
    })
}

/// why: None means no known conflict, not "confirmed conflict-free"
pub fn stacking_group_of(name: &str) -> Option<u32> {
    stacking_groups().get(name).copied()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_real_classic_poison_line_resolves_its_group() {
        assert_eq!(stacking_group_of("Scourge"), Some(86));
        assert_eq!(stacking_group_of("Plague"), Some(86));
    }

    #[test]
    fn an_unlisted_spell_is_none_not_a_fabricated_group() {
        assert_eq!(stacking_group_of("Ice Comet"), None);
    }
}
