//! why: recipe catalog for the 9 core tradeskills, baked in at compile
//! time like `classdata.rs`.
//!
//! Generated by `~/eql/scrape_eqlwiki_tradeskills.py` -- re-run and
//! re-copy to pick up wiki changes. See that script's own doc for the
//! real, confirmed wiki quirks it already accounts for (three
//! incompatible recipe-table shapes, a caption row before the real
//! header on some pages, named component-slot columns instead of one
//! combined column) and the ones it doesn't (a long tail of one-off
//! armor-material sub-tables with their own uniquely-named columns --
//! skipped and counted, not guessed at).

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::OnceLock;

const TRADESKILL_DATA_JSON: &str = include_str!("../../../packs/tradeskills.json");

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct RecipeIngredient {
    pub item: String,
    pub qty: u32,
    /// why: a container/tool consumed by the combine but handed back
    /// either way (e.g. a Pie Tin) -- not actually spent
    #[serde(default)]
    pub returned: bool,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Recipe {
    pub item: String,
    /// why: some output cells carry their own yield prefix ("2x [[Item]]")
    /// instead of a separate Yield column -- see the scraper's own doc
    #[serde(default = "one")]
    pub yield_qty: u32,
    pub ingredients: Vec<RecipeIngredient>,
    pub implements: Option<String>,
    /// why: raw text from a real "Yield" column, when one exists --
    /// distinct from yield_qty (which comes from the item cell itself)
    pub r#yield: Option<String>,
    /// why: None when the wiki's own trivial value isn't a plain
    /// integer ("?", "<67", etc. all appear for real) -- see trivial_raw
    pub trivial: Option<u32>,
    pub trivial_raw: Option<String>,
    pub r#use: Option<String>,
}

fn one() -> u32 {
    1
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct TradeskillSkill {
    pub skill: String,
    pub recipes: Vec<Recipe>,
}

#[derive(Debug, Deserialize)]
struct TradeskillsDoc {
    skills: Vec<TradeskillSkill>,
}

static TRADESKILLS: OnceLock<Vec<TradeskillSkill>> = OnceLock::new();

/// why: every scraped tradeskill's recipe list, parsed once; malformed
/// data fails loud
pub fn skills() -> &'static [TradeskillSkill] {
    TRADESKILLS
        .get_or_init(|| {
            let doc: TradeskillsDoc = serde_json::from_str(TRADESKILL_DATA_JSON)
                .unwrap_or_else(|e| panic!("packs/tradeskills.json failed to parse: {e}"));
            doc.skills
        })
        .as_slice()
}

/// why: a real output item name -> which skill(s) it's a recipe *for*,
/// case-insensitive -- lets the frontend cross-link "this ingredient is
/// itself craftable via Tailoring" between skills, not just within one
fn skill_by_output_item() -> &'static HashMap<String, &'static str> {
    static MAP: OnceLock<HashMap<String, &'static str>> = OnceLock::new();
    MAP.get_or_init(|| {
        let mut m = HashMap::new();
        for s in skills() {
            for r in &s.recipes {
                // why: first skill wins on a name collision across
                // skills (rare, and either answer is a real "yes, this
                // is craftable somewhere" -- not worth picking a "right" one)
                m.entry(r.item.to_ascii_lowercase())
                    .or_insert(s.skill.as_str());
            }
        }
        m
    })
}

/// why: None means "not a known recipe output anywhere" -- an honest
/// "buy/loot this" answer, not a guess
pub fn crafted_via(item: &str) -> Option<&'static str> {
    skill_by_output_item()
        .get(&item.to_ascii_lowercase())
        .copied()
}
