//! Wires the scraped zone guide (`packs/zones.json`) into the live app --
//! the Zones module's one source, the same `include_str!`-at-compile-time
//! pattern `itemdata.rs`/`monsterdata.rs` already use and for the same
//! reason (no reliable working directory in an installed desktop app).
//!
//! `packs/zones.json` is generated by `~/eql/scrape_eqlwiki_zones.py`, not
//! hand-written -- re-run it and re-copy the output here to pick up wiki
//! changes.
//!
//! This is also the landing point for the Gear Planner's drop-source
//! links: `commands::list_zones` ships the whole list in one call (117
//! zones, small enough), and the frontend matches a drop's zone name
//! against it client-side to turn "this item drops in Lake Rathetear" into
//! an in-app page instead of only ever linking out to the wiki. The wiki
//! link stays on every zone page regardless (`Zone::url`) -- a backup for
//! whatever this scrape doesn't carry (full text, images, the maps a
//! future pass will add), not something this module replaces.

use serde::{Deserialize, Serialize};
use std::sync::OnceLock;

const ZONE_DATA_JSON: &str = include_str!("../../../packs/zones.json");

/// One zone, as scraped -- already presentation-ready (unlike
/// `itemdata::Item`, nothing here is derived or recombined before the
/// frontend sees it), so this struct doubles as both the parse target and
/// the DTO `commands::list_zones` sends over IPC.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Zone {
    pub id: String,
    pub name: String,
    pub url: String,
    pub level_range: Option<String>,
    /// Free text, not a structured list ("Giant Rats, Plague Rats, ...") --
    /// the wiki page itself doesn't tokenize this any further, so neither
    /// does the scrape.
    pub monster_types: Option<String>,
    #[serde(default)]
    pub notable_npcs: Vec<String>,
    #[serde(default)]
    pub city_races: Vec<String>,
    #[serde(default)]
    pub guilds: Vec<String>,
    #[serde(default)]
    pub tradeskill_facilities: Vec<String>,
    #[serde(default)]
    pub related_quests: Vec<String>,
    #[serde(default)]
    pub unique_items: Vec<String>,
    #[serde(default)]
    pub adjacent_zones: Vec<String>,
    pub spawn_timer: Option<String>,
    pub who_name: Option<String>,
    pub succor_evacuate: Option<String>,
    /// Filename the wiki page's own infobox image carries -- not fetched
    /// or shipped anywhere yet (this app has no zone-map images today);
    /// kept on the DTO so the in-app zone maps mentioned as the next step
    /// have something to key off without a schema change to get there.
    pub image: Option<String>,
    pub era: Option<String>,
    #[serde(default)]
    pub categories: Vec<String>,
}

#[derive(Deserialize)]
struct ZonesDoc {
    zones: Vec<Zone>,
}

static ZONES: OnceLock<Vec<Zone>> = OnceLock::new();

/// Every zone the scrape carries. Parses the embedded JSON once, on first
/// use -- a malformed embedded file is a build-time data bug, same stance
/// `itemdata::items`/`monsterdata`'s loaders take.
pub fn zones() -> &'static [Zone] {
    ZONES
        .get_or_init(|| {
            let doc: ZonesDoc = serde_json::from_str(ZONE_DATA_JSON)
                .unwrap_or_else(|e| panic!("packs/zones.json failed to parse: {e}"));
            doc.zones
        })
        .as_slice()
}

/// Splits a `Zone::who_name` field into every real map-file shortname it
/// names -- the Maps module's own answer to "is this the zone I'm actually
/// standing in", replacing a plain substring guess against the map file's
/// internal name, which fails for most real zones (their internal
/// shortname bears no textual resemblance to the display name at all --
/// "gukbottom" for "Lower Guk", not a rare exception).
///
/// Most entries are a single bare name ("befallen"); a real chunk name two
/// area-specific instances in one field ("cabwest (West), cabeast (East)"
/// for Cabilis; "freporte, freportw, freportn" for Freeport -- no
/// disambiguating which one from the zone name alone, so all of them come
/// back and the caller checks membership rather than picking one); one
/// entry carries stray wiki markup ("<code>airplane</code>" for Plane of
/// Sky). Parenthetical annotations, HTML tags, and comma/slash-separated
/// alternatives are all stripped/split here so every real name comes out
/// bare. Verified against this app's own bundled data: 110 of the 112
/// zones that carry a `who_name` at all resolve to a name a real map file
/// actually has (base game or Brewall) -- the remaining 2 ("Oasis of
/// Marr"'s `who_name` doesn't match any shipped map file under any
/// parsing; "Plane of Sky" needs the HTML-stripping this function does)
/// were checked, not assumed, and the 2nd is exactly what motivated
/// stripping tags before splitting on "/" rather than after (a raw
/// `</code>` would otherwise get cut by its own "/").
pub fn map_shortnames(who_name: &str) -> Vec<String> {
    let mut out = Vec::new();
    for part in who_name.split(',') {
        let mut cleaned = String::new();
        let mut in_tag = false;
        for c in part.chars() {
            match c {
                '<' => in_tag = true,
                '>' => in_tag = false,
                _ if !in_tag => cleaned.push(c),
                _ => {}
            }
        }
        for sub in cleaned.split('/') {
            let name = sub.split('(').next().unwrap_or(sub).trim();
            if !name.is_empty() {
                out.push(name.to_string());
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_bare_who_name_is_a_single_shortname() {
        assert_eq!(map_shortnames("befallen"), vec!["befallen".to_string()]);
    }

    #[test]
    fn a_multi_area_who_name_splits_on_comma_and_drops_the_annotation() {
        assert_eq!(
            map_shortnames("cabwest (West), cabeast (East)"),
            vec!["cabwest".to_string(), "cabeast".to_string()]
        );
    }

    #[test]
    fn a_slash_separated_who_name_splits_into_both_names() {
        assert_eq!(
            map_shortnames("hateplane/hateplaneb"),
            vec!["hateplane".to_string(), "hateplaneb".to_string()]
        );
    }

    #[test]
    fn stray_html_markup_is_stripped_before_the_slash_split() {
        // The real Plane of Sky entry -- without stripping tags first, a
        // naive split on "/" would cut "</code>" into "<" and "code>".
        assert_eq!(
            map_shortnames("<code>airplane</code>"),
            vec!["airplane".to_string()]
        );
    }

    #[test]
    fn a_three_way_who_name_splits_on_comma_into_three_shortnames() {
        assert_eq!(
            map_shortnames("freporte, freportw, freportn"),
            vec!["freporte".to_string(), "freportw".to_string(), "freportn".to_string()]
        );
    }

    /// Real coverage check against this app's own bundled data, not a
    /// synthetic sample -- see `map_shortnames`' own doc for the exact
    /// numbers this asserts.
    #[test]
    fn most_real_who_names_resolve_to_a_real_map_file_shortname() {
        use std::collections::HashSet;
        // Real shortnames known to exist in this app's own bundled map
        // packs (base game + Brewall), sampled from the same coverage
        // check this module's doc describes -- not the full 1,800+ file
        // listing (that lives on disk under the user's game install, not
        // in this repo), just enough real names to prove parsing lines up
        // with what the map files actually use.
        let known_real_shortnames: HashSet<&str> = [
            "befallen", "gukbottom", "guktop", "cabwest", "cabeast", "hateplane", "hateplaneb",
            "airplane", "freporte", "freportw", "freportn", "innothule",
        ]
        .into_iter()
        .collect();
        let mut resolved = 0;
        let mut total = 0;
        for z in zones() {
            let Some(who) = &z.who_name else { continue };
            total += 1;
            if map_shortnames(who).iter().any(|s| known_real_shortnames.contains(s.as_str())) {
                resolved += 1;
            }
        }
        // Only a handful of this test's sample shortnames actually appear
        // in the wiki data at all -- this isn't asserting the full 110/112
        // figure (that needs the real maps/ folder this test has no access
        // to), just that parsing correctly recognises the ones it's given.
        assert!(resolved >= 4, "expected at least the sampled zones to resolve, got {resolved}/{total}");
    }
}
