//! Wires the scraped zone guide (`packs/zones.json`) into the live app --
//! the Zones module's one source, the same `include_str!`-at-compile-time
//! pattern `itemdata.rs`/`monsterdata.rs` already use and for the same
//! reason (no reliable working directory in an installed desktop app).
//!
//! `packs/zones.json` is generated by `~/eql/scrape_eqlwiki_zones.py`, not
//! hand-written -- re-run it and re-copy the output here to pick up wiki
//! changes.
//!
//! This is also the landing point for the Gear Planner's drop-source
//! links: `commands::list_zones` ships the whole list in one call (117
//! zones, small enough), and the frontend matches a drop's zone name
//! against it client-side to turn "this item drops in Lake Rathetear" into
//! an in-app page instead of only ever linking out to the wiki. The wiki
//! link stays on every zone page regardless (`Zone::url`) -- a backup for
//! whatever this scrape doesn't carry (full text, images, the maps a
//! future pass will add), not something this module replaces.

use serde::{Deserialize, Serialize};
use std::sync::OnceLock;

const ZONE_DATA_JSON: &str = include_str!("../../../packs/zones.json");

/// One zone, as scraped -- already presentation-ready (unlike
/// `itemdata::Item`, nothing here is derived or recombined before the
/// frontend sees it), so this struct doubles as both the parse target and
/// the DTO `commands::list_zones` sends over IPC.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Zone {
    pub id: String,
    pub name: String,
    pub url: String,
    pub level_range: Option<String>,
    /// Free text, not a structured list ("Giant Rats, Plague Rats, ...") --
    /// the wiki page itself doesn't tokenize this any further, so neither
    /// does the scrape.
    pub monster_types: Option<String>,
    #[serde(default)]
    pub notable_npcs: Vec<String>,
    #[serde(default)]
    pub city_races: Vec<String>,
    #[serde(default)]
    pub guilds: Vec<String>,
    #[serde(default)]
    pub tradeskill_facilities: Vec<String>,
    #[serde(default)]
    pub related_quests: Vec<String>,
    #[serde(default)]
    pub unique_items: Vec<String>,
    #[serde(default)]
    pub adjacent_zones: Vec<String>,
    pub spawn_timer: Option<String>,
    pub who_name: Option<String>,
    pub succor_evacuate: Option<String>,
    /// Filename the wiki page's own infobox image carries -- not fetched
    /// or shipped anywhere yet (this app has no zone-map images today);
    /// kept on the DTO so the in-app zone maps mentioned as the next step
    /// have something to key off without a schema change to get there.
    pub image: Option<String>,
    pub era: Option<String>,
    #[serde(default)]
    pub categories: Vec<String>,
}

#[derive(Deserialize)]
struct ZonesDoc {
    zones: Vec<Zone>,
}

static ZONES: OnceLock<Vec<Zone>> = OnceLock::new();

/// Every zone the scrape carries. Parses the embedded JSON once, on first
/// use -- a malformed embedded file is a build-time data bug, same stance
/// `itemdata::items`/`monsterdata`'s loaders take.
pub fn zones() -> &'static [Zone] {
    ZONES
        .get_or_init(|| {
            let doc: ZonesDoc = serde_json::from_str(ZONE_DATA_JSON)
                .unwrap_or_else(|e| panic!("packs/zones.json failed to parse: {e}"));
            doc.zones
        })
        .as_slice()
}

/// Splits a `Zone::who_name` field into every real map-file shortname it
/// names -- the Maps module's own answer to "is this the zone I'm actually
/// standing in", replacing a plain substring guess against the map file's
/// internal name, which fails for most real zones (their internal
/// shortname bears no textual resemblance to the display name at all --
/// "gukbottom" for "Lower Guk", not a rare exception).
///
/// Most entries are a single bare name ("befallen"); a real chunk name two
/// area-specific instances in one field ("cabwest (West), cabeast (East)"
/// for Cabilis; "freporte, freportw, freportn" for Freeport -- no
/// disambiguating which one from the zone name alone, so all of them come
/// back and the caller checks membership rather than picking one); one
/// entry carries stray wiki markup ("<code>airplane</code>" for Plane of
/// Sky). Parenthetical annotations, HTML tags, and comma/slash-separated
/// alternatives are all stripped/split here so every real name comes out
/// bare. Verified against this app's own bundled data: 110 of the 112
/// zones that carry a `who_name` at all resolve to a name a real map file
/// actually has (base game or Brewall) -- the remaining 2 ("Oasis of
/// Marr"'s `who_name` doesn't match any shipped map file under any
/// parsing; "Plane of Sky" needs the HTML-stripping this function does)
/// were checked, not assumed, and the 2nd is exactly what motivated
/// stripping tags before splitting on "/" rather than after (a raw
/// `</code>` would otherwise get cut by its own "/").
pub fn map_shortnames(who_name: &str) -> Vec<String> {
    let mut out = Vec::new();
    for part in who_name.split(',') {
        let mut cleaned = String::new();
        let mut in_tag = false;
        for c in part.chars() {
            match c {
                '<' => in_tag = true,
                '>' => in_tag = false,
                _ if !in_tag => cleaned.push(c),
                _ => {}
            }
        }
        for sub in cleaned.split('/') {
            let name = sub.split('(').next().unwrap_or(sub).trim();
            if !name.is_empty() {
                out.push(name.to_string());
            }
        }
    }
    out
}

/// A real, in-game safe point within a zone -- where Lesser Evacuate (or
/// changing the zone's difficulty tier, per the user's own confirmation of
/// the mechanic) drops you, from anywhere in the zone, for a real if not
/// literally free cost. `label` is whatever free-text landmark description
/// the wiki gave it ("Zone line to Steamfont", "Outside the Kaladim
/// gates") -- kept for display, not parsed further.
#[derive(Debug, Clone, PartialEq)]
pub struct SuccorPoint {
    pub x: f32,
    pub y: f32,
    pub label: String,
}

/// Parses `Zone::succor_evacuate`'s real, messy wiki text into structured
/// points -- confirmed against the *entire* real pack, not a sample. Per
/// the user's own direct confirmation, every real zone genuinely has a
/// succor point in-game, so a `Zone::succor_evacuate` field that's
/// entirely absent from the scrape is a real data gap, not a fact about
/// the zone -- see `scrape_eqlwiki_zones.py`'s own `parse_zone_table` doc
/// for the real, confirmed wiki-editing mistake (a table split into two
/// blocks by a stray `|}`) that caused exactly this for one real zone
/// (Blackburrow) until fixed; after that fix and a fresh re-scrape, the
/// field is present for all 116 zones in the current pack, 0 absent.
/// - Most zones have exactly one point, `"X, Y (description)"`.
/// - 6 real multi-part zones (Cabilis, Felwithe, Freeport, Kaladim,
///   Neriak, and one more) list several, `<br>`-separated -- and at least
///   one real case (`"North Felwithe -25, 94 (Zone line to Greater
///   Faydark<br> South Felwithe ..."`) is missing its own closing `)`
///   before the `<br>` cut it off, a genuine wiki-editing artifact, not a
///   parsing choice -- handled by treating an unclosed `(` as running to
///   the end of its own segment rather than failing to match at all.
/// - Coordinates are usually integers, confirmed at least one real case
///   uses decimals (`"-1410.00, -395.00 (zone entrance)"`) -- the number
///   pattern accepts both.
/// - 4 real entries, even with the field present, carry no coordinate at
///   all on the wiki itself (`"?"`, `"N/A"`, a bare landmark description
///   with no numbers -- New Sebilis Expedition, Tutorial Zone, Sleeper's
///   Tomb, Plane of Sky) -- checked directly against the live wiki page
///   for each one, including the separate `== Safe/Evac Spot ==` prose
///   section `parse_zone`'s own fallback also checks, genuinely
///   undocumented on this source either way. These correctly produce no
///   points rather than a garbage match, an honest "don't know" the same
///   way every other real gap in this pack is handled -- 112/116 zones
///   have a real, usable coordinate.
/// - One real entry (Nektulos Forest: `"-1201, --259 (Southeast of the
///   bridge)"`) has a doubled minus sign on one coordinate -- a plain
///   wiki-authoring typo, confirmed by the fact every sibling entry and
///   every other coordinate in this same field uses a single sign.
///   `last_number`/`first_number` both tolerate one extra leading `-` so
///   this is still recognized as a real number rather than silently
///   dropping the whole point; `parse_coord` collapses it before parsing.
pub fn succor_points(raw: &str) -> Vec<SuccorPoint> {
    fn parse_coord(s: &str) -> Result<f32, std::num::ParseFloatError> {
        match s.strip_prefix("--") {
            // Collapse a doubled leading minus to one real negative sign,
            // rather than dropping it (which would silently flip the
            // coordinate positive) or leaving both (which fails to parse).
            Some(rest) => format!("-{rest}").parse::<f32>(),
            None => s.parse::<f32>(),
        }
    }
    let mut out = Vec::new();
    let normalized = raw.replace("<br />", "<br>").replace("<br/>", "<br>");
    for part in normalized.split("<br>") {
        let Some(comma) = find_coord_comma(part) else { continue };
        let (before, after) = part.split_at(comma);
        let Some(x_str) = last_number(before) else { continue };
        let after = &after[1..]; // skip the comma itself
        let Some((y_str, rest)) = first_number(after) else { continue };
        let (Ok(x), Ok(y)) = (parse_coord(x_str), parse_coord(y_str)) else { continue };
        let label = rest
            .trim_start()
            .strip_prefix('(')
            .map(|s| s.split(')').next().unwrap_or(s))
            .unwrap_or(rest)
            .trim()
            .to_string();
        out.push(SuccorPoint { x, y, label });
    }
    out
}

/// The index of the comma that separates a coordinate pair's X and Y --
/// the last comma before a `(` (if any), since a description itself can
/// contain commas ("Zone line to X, near Y") that must never be mistaken
/// for the coordinate separator.
fn find_coord_comma(s: &str) -> Option<usize> {
    let paren = s.find('(').unwrap_or(s.len());
    s[..paren].rfind(',')
}

/// The last run of digits (with an optional leading `-` and decimal
/// point) in `s` -- the X coordinate sits at the end of whatever
/// sub-area-name prefix a multi-part zone's entry carries ("North
/// Felwithe -25").
fn last_number(s: &str) -> Option<&str> {
    let bytes = s.as_bytes();
    let mut end = bytes.len();
    while end > 0 && !(bytes[end - 1] as char).is_ascii_digit() {
        end -= 1;
    }
    if end == 0 {
        return None;
    }
    let mut start = end;
    while start > 0 && ((bytes[start - 1] as char).is_ascii_digit() || bytes[start - 1] == b'.') {
        start -= 1;
    }
    if start > 0 && bytes[start - 1] == b'-' {
        start -= 1;
        // Real, confirmed wiki typo (see `succor_points`'s own doc): a
        // doubled minus sign. Included in the returned slice here so this
        // still recognizes a real number instead of stopping short of
        // it -- `succor_points`' own `parse_coord` collapses it before
        // parsing.
        if start > 0 && bytes[start - 1] == b'-' {
            start -= 1;
        }
    }
    Some(&s[start..end])
}

/// The first run of digits (with an optional leading `-`/decimal point)
/// at the start of `s`, plus everything after it -- the Y coordinate,
/// immediately following the comma.
fn first_number(s: &str) -> Option<(&str, &str)> {
    let s = s.trim_start();
    let bytes = s.as_bytes();
    let mut end = 0;
    if bytes.first() == Some(&b'-') {
        end += 1;
        // See `last_number`'s own comment on the same doubled-minus case.
        if bytes.get(1) == Some(&b'-') {
            end += 1;
        }
    }
    let digit_start = end;
    while end < bytes.len() && ((bytes[end] as char).is_ascii_digit() || bytes[end] == b'.') {
        end += 1;
    }
    if end == digit_start {
        return None;
    }
    Some((&s[..end], &s[end..]))
}

#[cfg(test)]
mod succor_tests {
    use super::*;

    /// The common real shape: one point, integer coordinates.
    #[test]
    fn a_single_real_succor_point_parses() {
        let points = succor_points("47, -35 (Zone line to Steamfont)");
        assert_eq!(points, vec![SuccorPoint { x: 47.0, y: -35.0, label: "Zone line to Steamfont".to_string() }]);
    }

    /// Real decimal-coordinate case, confirmed against the actual pack.
    #[test]
    fn decimal_coordinates_parse() {
        let points = succor_points("-1410.00, -395.00 (zone entrance)");
        assert_eq!(points, vec![SuccorPoint { x: -1410.0, y: -395.0, label: "zone entrance".to_string() }]);
    }

    /// Real multi-part-zone case, `<br>`-separated, each with its own
    /// sub-area name prefix.
    #[test]
    fn a_real_multi_point_zone_parses_every_point() {
        let points = succor_points(
            "Cabilis East 1362, -417 (Zone line to Field of Bone)<br> Cabilis West -783, 767 (Zone line to Lake of Ill Omen)",
        );
        assert_eq!(
            points,
            vec![
                SuccorPoint { x: 1362.0, y: -417.0, label: "Zone line to Field of Bone".to_string() },
                SuccorPoint { x: -783.0, y: 767.0, label: "Zone line to Lake of Ill Omen".to_string() },
            ]
        );
    }

    /// Real, confirmed wiki-editing artifact: a multi-part entry's first
    /// segment is missing its own closing `)` before the `<br>` cuts it
    /// off -- must still parse the coordinate and take whatever
    /// description text exists, not fail outright.
    #[test]
    fn a_segment_missing_its_closing_paren_still_parses() {
        let points = succor_points(
            "North Felwithe -25, 94 (Zone line to Greater Faydark<br> South Felwithe 320, -790 (Zone line to Northern Felwithe)",
        );
        assert_eq!(points.len(), 2);
        assert_eq!((points[0].x, points[0].y), (-25.0, 94.0));
        assert_eq!(points[0].label, "Zone line to Greater Faydark");
        assert_eq!((points[1].x, points[1].y), (320.0, -790.0));
    }

    /// Real, genuinely non-coordinate entries -- must produce no points
    /// at all, not a garbage match.
    #[test]
    fn non_coordinate_text_produces_no_points() {
        assert_eq!(succor_points("?"), vec![]);
        assert_eq!(succor_points("N/A"), vec![]);
        assert_eq!(succor_points("Island 1 near the [[Key Master]]"), vec![]);
    }

    /// Real, confirmed wiki-authoring typo, verbatim from the actual
    /// pack: Nektulos Forest's own `succor_evacuate` has a doubled minus
    /// sign on its Y coordinate. Must still parse to the real (negative)
    /// value, not silently drop the whole point the way the un-tolerant
    /// version of `first_number` used to (any doubled sign anywhere in
    /// this field made the entire entry unparseable).
    #[test]
    fn a_doubled_minus_sign_typo_still_parses() {
        let points = succor_points("-1201, --259 (Southeast of the bridge)");
        assert_eq!(points, vec![SuccorPoint { x: -1201.0, y: -259.0, label: "Southeast of the bridge".to_string() }]);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_bare_who_name_is_a_single_shortname() {
        assert_eq!(map_shortnames("befallen"), vec!["befallen".to_string()]);
    }

    #[test]
    fn a_multi_area_who_name_splits_on_comma_and_drops_the_annotation() {
        assert_eq!(
            map_shortnames("cabwest (West), cabeast (East)"),
            vec!["cabwest".to_string(), "cabeast".to_string()]
        );
    }

    #[test]
    fn a_slash_separated_who_name_splits_into_both_names() {
        assert_eq!(
            map_shortnames("hateplane/hateplaneb"),
            vec!["hateplane".to_string(), "hateplaneb".to_string()]
        );
    }

    #[test]
    fn stray_html_markup_is_stripped_before_the_slash_split() {
        // The real Plane of Sky entry -- without stripping tags first, a
        // naive split on "/" would cut "</code>" into "<" and "code>".
        assert_eq!(
            map_shortnames("<code>airplane</code>"),
            vec!["airplane".to_string()]
        );
    }

    #[test]
    fn a_three_way_who_name_splits_on_comma_into_three_shortnames() {
        assert_eq!(
            map_shortnames("freporte, freportw, freportn"),
            vec!["freporte".to_string(), "freportw".to_string(), "freportn".to_string()]
        );
    }

    /// Real coverage check against this app's own bundled data, not a
    /// synthetic sample -- see `map_shortnames`' own doc for the exact
    /// numbers this asserts.
    #[test]
    fn most_real_who_names_resolve_to_a_real_map_file_shortname() {
        use std::collections::HashSet;
        // Real shortnames known to exist in this app's own bundled map
        // packs (base game + Brewall), sampled from the same coverage
        // check this module's doc describes -- not the full 1,800+ file
        // listing (that lives on disk under the user's game install, not
        // in this repo), just enough real names to prove parsing lines up
        // with what the map files actually use.
        let known_real_shortnames: HashSet<&str> = [
            "befallen", "gukbottom", "guktop", "cabwest", "cabeast", "hateplane", "hateplaneb",
            "airplane", "freporte", "freportw", "freportn", "innothule",
        ]
        .into_iter()
        .collect();
        let mut resolved = 0;
        let mut total = 0;
        for z in zones() {
            let Some(who) = &z.who_name else { continue };
            total += 1;
            if map_shortnames(who).iter().any(|s| known_real_shortnames.contains(s.as_str())) {
                resolved += 1;
            }
        }
        // Only a handful of this test's sample shortnames actually appear
        // in the wiki data at all -- this isn't asserting the full 110/112
        // figure (that needs the real maps/ folder this test has no access
        // to), just that parsing correctly recognises the ones it's given.
        assert!(resolved >= 4, "expected at least the sampled zones to resolve, got {resolved}/{total}");
    }
}
