//! why: zone guide, baked in like `itemdata.rs`/`monsterdata.rs` -- the Zones module's one source
//!
//! Generated by `~/eql/scrape_eqlwiki_zones.py`. Also the Gear Planner's
//! drop-source link target: `list_zones` ships all 117 zones at once,
//! frontend matches client-side. `Zone::url` stays as a wiki backup for
//! whatever the scrape doesn't carry.

use serde::{Deserialize, Serialize};
use std::sync::OnceLock;

const ZONE_DATA_JSON: &str = include_str!("../../../packs/zones.json");

/// why: presentation-ready, unlike `itemdata::Item` -- doubles as parse target and DTO
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Zone {
    pub id: String,
    pub name: String,
    pub url: String,
    pub level_range: Option<String>,
    /// why: free text, the wiki page itself doesn't tokenize this further
    pub monster_types: Option<String>,
    #[serde(default)]
    pub notable_npcs: Vec<String>,
    #[serde(default)]
    pub city_races: Vec<String>,
    #[serde(default)]
    pub guilds: Vec<String>,
    #[serde(default)]
    pub tradeskill_facilities: Vec<String>,
    #[serde(default)]
    pub related_quests: Vec<String>,
    #[serde(default)]
    pub unique_items: Vec<String>,
    #[serde(default)]
    pub adjacent_zones: Vec<String>,
    pub spawn_timer: Option<String>,
    pub who_name: Option<String>,
    pub succor_evacuate: Option<String>,
    /// why: infobox image filename, not fetched yet; kept for a future zone-map pass
    pub image: Option<String>,
    pub era: Option<String>,
    #[serde(default)]
    pub categories: Vec<String>,
}

#[derive(Deserialize)]
struct ZonesDoc {
    zones: Vec<Zone>,
}

static ZONES: OnceLock<Vec<Zone>> = OnceLock::new();

/// why: every scraped zone, parsed once; malformed data fails loud
pub fn zones() -> &'static [Zone] {
    ZONES
        .get_or_init(|| {
            let doc: ZonesDoc = serde_json::from_str(ZONE_DATA_JSON)
                .unwrap_or_else(|e| panic!("packs/zones.json failed to parse: {e}"));
            doc.zones
        })
        .as_slice()
}

/// why: splits `who_name` into real map-file shortnames -- internal
/// shortnames bear no resemblance to display names ("gukbottom" for
/// "Lower Guk"). Some fields name multiple areas with no way to
/// disambiguate, so all come back and the caller checks membership.
/// Strips tags before splitting on "/" -- verified 110/112 zones resolve
/// to a real map file, the other 2 checked individually and confirmed gaps.
pub fn map_shortnames(who_name: &str) -> Vec<String> {
    let mut out = Vec::new();
    for part in who_name.split(',') {
        let mut cleaned = String::new();
        let mut in_tag = false;
        for c in part.chars() {
            match c {
                '<' => in_tag = true,
                '>' => in_tag = false,
                _ if !in_tag => cleaned.push(c),
                _ => {}
            }
        }
        for sub in cleaned.split('/') {
            let name = sub.split('(').next().unwrap_or(sub).trim();
            if !name.is_empty() {
                out.push(name.to_string());
            }
        }
    }
    out
}

/// why: where Lesser Evacuate (or a tier change) drops you; `label` is raw wiki text
#[derive(Debug, Clone, PartialEq)]
pub struct SuccorPoint {
    pub x: f32,
    pub y: f32,
    pub label: String,
}

/// why: parses `succor_evacuate`'s messy wiki text into structured points,
/// confirmed against the entire real pack. Every real zone has a succor
/// point in-game, so an absent field is a data gap, not a zone fact
/// (fixed for Blackburrow: a wiki table split by a stray `|}`).
/// - most zones: one point, "X, Y (description)"
/// - 6 multi-part zones: `<br>`-separated, one real entry missing its
///   closing `)` (wiki-editing artifact, handled not failed)
/// - coordinates usually integers, confirmed decimals also occur
/// - 4 entries genuinely have no coordinate at all -- correctly produce
///   no points, an honest gap (112/116 zones have a usable coordinate)
/// - Nektulos Forest has a doubled-minus typo, tolerated not dropped
pub fn succor_points(raw: &str) -> Vec<SuccorPoint> {
    fn parse_coord(s: &str) -> Result<f32, std::num::ParseFloatError> {
        match s.strip_prefix("--") {
            // why: collapse doubled minus to one, not drop or leave both
            Some(rest) => format!("-{rest}").parse::<f32>(),
            None => s.parse::<f32>(),
        }
    }
    let mut out = Vec::new();
    let normalized = raw.replace("<br />", "<br>").replace("<br/>", "<br>");
    for part in normalized.split("<br>") {
        let Some(comma) = find_coord_comma(part) else {
            continue;
        };
        let (before, after) = part.split_at(comma);
        let Some(x_str) = last_number(before) else {
            continue;
        };
        let after = &after[1..]; // skip the comma itself
        let Some((y_str, rest)) = first_number(after) else {
            continue;
        };
        let (Ok(x), Ok(y)) = (parse_coord(x_str), parse_coord(y_str)) else {
            continue;
        };
        let label = rest
            .trim_start()
            .strip_prefix('(')
            .map(|s| s.split(')').next().unwrap_or(s))
            .unwrap_or(rest)
            .trim()
            .to_string();
        out.push(SuccorPoint { x, y, label });
    }
    out
}

/// why: last comma before `(` -- a description can contain commas of its own
fn find_coord_comma(s: &str) -> Option<usize> {
    let paren = s.find('(').unwrap_or(s.len());
    s[..paren].rfind(',')
}

/// why: X coordinate sits at the end of a multi-part zone's name prefix
fn last_number(s: &str) -> Option<&str> {
    let bytes = s.as_bytes();
    let mut end = bytes.len();
    while end > 0 && !(bytes[end - 1] as char).is_ascii_digit() {
        end -= 1;
    }
    if end == 0 {
        return None;
    }
    let mut start = end;
    while start > 0 && ((bytes[start - 1] as char).is_ascii_digit() || bytes[start - 1] == b'.') {
        start -= 1;
    }
    if start > 0 && bytes[start - 1] == b'-' {
        start -= 1;
        // why: doubled-minus typo, included so this still recognizes the
        // number; `parse_coord` collapses it before parsing
        if start > 0 && bytes[start - 1] == b'-' {
            start -= 1;
        }
    }
    Some(&s[start..end])
}

/// why: Y coordinate, immediately following the comma, plus the rest
fn first_number(s: &str) -> Option<(&str, &str)> {
    let s = s.trim_start();
    let bytes = s.as_bytes();
    let mut end = 0;
    if bytes.first() == Some(&b'-') {
        end += 1;
        // why: same doubled-minus case as `last_number`
        if bytes.get(1) == Some(&b'-') {
            end += 1;
        }
    }
    let digit_start = end;
    while end < bytes.len() && ((bytes[end] as char).is_ascii_digit() || bytes[end] == b'.') {
        end += 1;
    }
    if end == digit_start {
        return None;
    }
    Some((&s[..end], &s[end..]))
}

#[cfg(test)]
mod succor_tests {
    use super::*;

    /// why: common real shape, one point, integer coordinates
    #[test]
    fn a_single_real_succor_point_parses() {
        let points = succor_points("47, -35 (Zone line to Steamfont)");
        assert_eq!(
            points,
            vec![SuccorPoint {
                x: 47.0,
                y: -35.0,
                label: "Zone line to Steamfont".to_string()
            }]
        );
    }

    /// why: real decimal-coordinate case, confirmed against the actual pack
    #[test]
    fn decimal_coordinates_parse() {
        let points = succor_points("-1410.00, -395.00 (zone entrance)");
        assert_eq!(
            points,
            vec![SuccorPoint {
                x: -1410.0,
                y: -395.0,
                label: "zone entrance".to_string()
            }]
        );
    }

    /// why: real multi-part-zone case, `<br>`-separated with sub-area prefixes
    #[test]
    fn a_real_multi_point_zone_parses_every_point() {
        let points = succor_points(
            "Cabilis East 1362, -417 (Zone line to Field of Bone)<br> Cabilis West -783, 767 (Zone line to Lake of Ill Omen)",
        );
        assert_eq!(
            points,
            vec![
                SuccorPoint {
                    x: 1362.0,
                    y: -417.0,
                    label: "Zone line to Field of Bone".to_string()
                },
                SuccorPoint {
                    x: -783.0,
                    y: 767.0,
                    label: "Zone line to Lake of Ill Omen".to_string()
                },
            ]
        );
    }

    /// why: wiki-editing artifact -- missing closing `)` must still parse
    #[test]
    fn a_segment_missing_its_closing_paren_still_parses() {
        let points = succor_points(
            "North Felwithe -25, 94 (Zone line to Greater Faydark<br> South Felwithe 320, -790 (Zone line to Northern Felwithe)",
        );
        assert_eq!(points.len(), 2);
        assert_eq!((points[0].x, points[0].y), (-25.0, 94.0));
        assert_eq!(points[0].label, "Zone line to Greater Faydark");
        assert_eq!((points[1].x, points[1].y), (320.0, -790.0));
    }

    /// why: genuinely non-coordinate entries must produce no points, not a garbage match
    #[test]
    fn non_coordinate_text_produces_no_points() {
        assert_eq!(succor_points("?"), vec![]);
        assert_eq!(succor_points("N/A"), vec![]);
        assert_eq!(succor_points("Island 1 near the [[Key Master]]"), vec![]);
    }

    /// why: real wiki typo, doubled minus sign, must still parse not drop
    #[test]
    fn a_doubled_minus_sign_typo_still_parses() {
        let points = succor_points("-1201, --259 (Southeast of the bridge)");
        assert_eq!(
            points,
            vec![SuccorPoint {
                x: -1201.0,
                y: -259.0,
                label: "Southeast of the bridge".to_string()
            }]
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_bare_who_name_is_a_single_shortname() {
        assert_eq!(map_shortnames("befallen"), vec!["befallen".to_string()]);
    }

    #[test]
    fn a_multi_area_who_name_splits_on_comma_and_drops_the_annotation() {
        assert_eq!(
            map_shortnames("cabwest (West), cabeast (East)"),
            vec!["cabwest".to_string(), "cabeast".to_string()]
        );
    }

    #[test]
    fn a_slash_separated_who_name_splits_into_both_names() {
        assert_eq!(
            map_shortnames("hateplane/hateplaneb"),
            vec!["hateplane".to_string(), "hateplaneb".to_string()]
        );
    }

    #[test]
    fn stray_html_markup_is_stripped_before_the_slash_split() {
        // why: real Plane of Sky entry -- without tag-stripping, "/" split would cut "</code>"
        assert_eq!(
            map_shortnames("<code>airplane</code>"),
            vec!["airplane".to_string()]
        );
    }

    #[test]
    fn a_three_way_who_name_splits_on_comma_into_three_shortnames() {
        assert_eq!(
            map_shortnames("freporte, freportw, freportn"),
            vec![
                "freporte".to_string(),
                "freportw".to_string(),
                "freportn".to_string()
            ]
        );
    }

    /// why: real coverage check against bundled data, not a synthetic sample
    #[test]
    fn most_real_who_names_resolve_to_a_real_map_file_shortname() {
        use std::collections::HashSet;
        // why: real bundled shortnames, sampled -- not the full on-disk listing
        let known_real_shortnames: HashSet<&str> = [
            "befallen",
            "gukbottom",
            "guktop",
            "cabwest",
            "cabeast",
            "hateplane",
            "hateplaneb",
            "airplane",
            "freporte",
            "freportw",
            "freportn",
            "innothule",
        ]
        .into_iter()
        .collect();
        let mut resolved = 0;
        let mut total = 0;
        for z in zones() {
            let Some(who) = &z.who_name else { continue };
            total += 1;
            if map_shortnames(who)
                .iter()
                .any(|s| known_real_shortnames.contains(s.as_str()))
            {
                resolved += 1;
            }
        }
        // why: not asserting the full 110/112 figure, just recognizing the sample
        assert!(
            resolved >= 4,
            "expected at least the sampled zones to resolve, got {resolved}/{total}"
        );
    }
}
