#!/usr/bin/env python3
"""gen_api_docs.py — generate docs/api/commands.md and docs/api/packs.md.

why: the command surface IS the plugin API; a hand-written catalog of 104
commands goes stale the first week. This reads the real sources:
  - commands.md from #[tauri::command] fns in crates/app/src/commands.rs
    (name, doc comment, params minus Tauri plumbing, return type, purity)
  - packs.md from packs/*.json (envelope fields, payload key, consumer
    module found by grepping include_str! sites, producer script if a
    tools/scrapers/ file mentions the pack name)
run: python3 tools/gen_api_docs.py   (from the repo root; rerun after
adding/changing a command or pack, commit the regenerated docs)
"""

import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COMMANDS_RS = ROOT / "crates/app/src/commands.rs"
PACKS = ROOT / "packs"
OUT = ROOT / "docs/api"

TAURI_PLUMBING = re.compile(r"^(app|_app|window|_window|state|_state)$")
PLUMBING_TYPES = ("State<", "AppHandle", "WebviewWindow", "Window")


def extract_commands(src: str):
    """Each #[tauri::command] with its preceding /// docs and signature."""
    out = []
    lines = src.split("\n")
    for i, line in enumerate(lines):
        if line.strip() != "#[tauri::command]":
            continue
        # doc comment: contiguous /// block immediately above
        docs = []
        j = i - 1
        while j >= 0 and lines[j].strip().startswith("///"):
            docs.insert(0, lines[j].strip().lstrip("/").strip())
            j -= 1
        # signature: from the next `pub fn` to the opening brace
        sig_lines = []
        k = i + 1
        while k < len(lines) and "pub fn" not in lines[k]:
            k += 1
        while k < len(lines):
            sig_lines.append(lines[k].strip())
            if "{" in lines[k] or lines[k].rstrip().endswith(";"):
                break
            k += 1
        sig = " ".join(sig_lines).split("{")[0].strip()
        m = re.match(r"pub fn (\w+)\s*\((.*?)\)\s*(?:->\s*(.+?))?\s*$", sig)
        if not m:
            out.append({"name": sig, "doc": " ".join(docs), "params": [], "ret": "?", "pure": False})
            continue
        name, rawparams, ret = m.group(1), m.group(2), (m.group(3) or "()").strip()
        params, pure = [], True
        # split params at top-level commas (angle-bracket aware)
        depth, cur, parts = 0, "", []
        for ch in rawparams:
            if ch in "<(":
                depth += 1
            elif ch in ">)":
                depth -= 1
            if ch == "," and depth == 0:
                parts.append(cur)
                cur = ""
            else:
                cur += ch
        if cur.strip():
            parts.append(cur)
        for p in parts:
            p = p.strip()
            if ":" not in p:
                continue
            pname, ptype = [s.strip() for s in p.split(":", 1)]
            if any(t in ptype for t in PLUMBING_TYPES):
                pure = False
                continue
            params.append(f"{pname}: {ptype}")
        out.append({"name": name, "doc": " ".join(docs), "params": params, "ret": ret, "pure": pure})
    return out


def write_commands_md(cmds):
    md = [
        "# Command catalog",
        "",
        "GENERATED by tools/gen_api_docs.py -- do not edit by hand; rerun the",
        "script after changing crates/app/src/commands.rs and commit the result.",
        "",
        "Every `#[tauri::command]` in commands.rs. **pure** commands read only",
        "their arguments and the static data packs -- they are the first",
        "candidates for exposure outside the Tauri shell. **stateful** commands",
        "read the live session (`AppState`: the ingest store, config, status)",
        "and need the service layer described in README.md before external",
        "exposure. Parameters shown are the real API surface -- Tauri plumbing",
        "(`State`, `AppHandle`, `Window`) is elided.",
        "",
        f"{len(cmds)} commands: "
        f"{sum(1 for c in cmds if c['pure'])} pure, "
        f"{sum(1 for c in cmds if not c['pure'])} stateful.",
        "",
    ]
    for c in sorted(cmds, key=lambda c: (not c["pure"], c["name"])):
        kind = "pure" if c["pure"] else "stateful"
        md.append(f"## `{c['name']}` ({kind})")
        if c["doc"]:
            md.append(f"{c['doc']}")
        md.append("")
        if c["params"]:
            md.append("- args: " + "; ".join(f"`{p}`" for p in c["params"]))
        else:
            md.append("- args: none")
        md.append(f"- returns: `{c['ret']}`")
        md.append("")
    (OUT / "commands.md").write_text("\n".join(md))
    return len(cmds)


ENVELOPE_KEYS = {"source", "scraped", "built", "from", "count", "note"}


def pack_consumer(pack_name: str) -> str:
    try:
        hits = subprocess.run(
            ["grep", "-rln", f"packs/{pack_name}", str(ROOT / "crates/app/src")],
            capture_output=True, text=True,
        ).stdout.split()
        return ", ".join(Path(h).name for h in hits) or "(unreferenced)"
    except OSError:
        return "?"


def pack_producer(pack_name: str) -> str:
    scrapers = ROOT / "tools/scrapers"
    if not scrapers.is_dir():
        return "?"
    for s in sorted(scrapers.glob("*.py")):
        if pack_name in s.read_text(errors="replace"):
            return s.name
    return "(no in-repo producer)"


def write_packs_md():
    md = [
        "# Data pack catalog",
        "",
        "GENERATED by tools/gen_api_docs.py -- do not edit by hand.",
        "",
        "Every packs/*.json: its envelope (provenance metadata), payload shape,",
        "the crates/app module that embeds it (via include_str!), and the",
        "tools/scrapers/ script that produces it. The standard envelope is",
        "`{source, scraped|built, count, <payload>}` -- packs listed with",
        "`(bare)` predate the standard and carry no provenance; see README.md.",
        "",
    ]
    for f in sorted(PACKS.glob("*.json")):
        d = json.loads(f.read_text())
        if isinstance(d, dict):
            env = sorted(ENVELOPE_KEYS & set(d.keys()))
            payload = [k for k in d.keys() if k not in ENVELOPE_KEYS and not k.startswith("skipped")]
            shape = f"envelope [{', '.join(env)}], payload key(s): {', '.join(payload[:3])}" if env else "(bare) top-level map, no envelope"
        else:
            shape = f"(bare) top-level list[{len(d)}]"
        md.append(f"## {f.name}")
        md.append(f"- shape: {shape}")
        md.append(f"- consumer: {pack_consumer(f.name)}")
        md.append(f"- producer: {pack_producer(f.name)}")
        md.append("")
    (OUT / "packs.md").write_text("\n".join(md))


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    n = write_commands_md(extract_commands(COMMANDS_RS.read_text()))
    write_packs_md()
    print(f"wrote docs/api/commands.md ({n} commands) and docs/api/packs.md")


if __name__ == "__main__":
    main()
